lots of stuff thats been culminating over the past few weeks, see the changelog. The main feature being commit depends on a cast success rather than as we run through the DEPENDS file.

diff --git a/usr/sbin/cast b/usr/sbin/cast
--- a/usr/sbin/cast
+++ b/usr/sbin/cast
@@ -40,7 +40,8 @@ Optional Parameters:
 -f  |  --fix			Discover and fix broken spells
 -n  |  --nofix			Discover, but do not fix broken spells
 
--d  |  --download		Force download of sources (overwrite existing files)
+-d  |  --download		Force download of sources (overwrite existing
+                                files)
 
 -s				Download 1st, cast 2nd
     |  --deps			Configure spells and determine dependencies,
@@ -48,7 +49,11 @@ Optional Parameters:
 
 -c  |  --compile		Ignore $INSTALL_CACHE and compiles
 -r  |  --reconfigure		Select new dependencies for spells
+-R  |  --recast-down		Recast depended-upon spells, even if they are
+                                already installed...
 
+-B  |  --recast-up		Recast dependent spells, even if they are
+                                already installed...
        --from	directory	Specify an alternate for $SOURCE_CACHE
        --url	URL		Specify an alternate download URL
 
@@ -62,39 +67,6 @@ EOF
   exit  1
 
 }
-
-
-
-function set_failed_cast() {     # this is never called... erics (2004-01-28)
-
-  debug "cast" "Function : set_failed_cast"
-
-  if [[ $FAILED_CASTS ]] ; then
-    FAILED_CASTS="$FAILED_CASTS $SPELL"
-  else
-    FAILED_CASTS="$SPELL"
-  fi
-
-  debug "set_failed_cast" "Value for FAILED CASTS : '$FAILED_CASTS'"
-
-}
-
-# this is called from resurrect, but the global variable it sets
-# isn't used anywhere astitt (2004-03-12)
-function set_successful_cast() {
-  
-  debug "cast" "Function : set_successful_cast"
-
-  if [[ $SUCCESSFUL_CASTS ]] ; then
-    SUCCESSFUL_CASTS="$SUCCESSFUL_CASTS $SPELL"
-  else
-    SUCCESSFUL_CASTS="$SPELL"
-  fi
-
-  debug "set_successful_cast" "Value for SUCCESSFUL CASTS : '$SUCCESSFUL_CASTS'"
-
-}
-
 
 
 function lib_dirs()  {
@@ -315,7 +287,7 @@ function sym_check()  { (
 ) }
 
 
-md5sum_check()  { (
+function md5sum_check()  { (
 
   if  [  "$MD5SUM_CHECK"  ==  "off"  ];  then
     return
@@ -554,6 +526,8 @@ function process_parameters()  {
 	    -t|--dot)  export DOT_PROGRESS='-dot' ;      shift 1  ;;
               --deps)  export  DEPS_ONLY="$1";           shift 1  ;;
     -r|--reconfigure)  RECONFIGURE="$1";                 shift 1  ;;
+         -R|--recast)  RECAST_DOWN="$1";                 shift 1  ;;
+         -B|--recast)  RECAST_UP="$1";                   shift 1  ;;
         -c|--compile)  COMPILE="$1";                     shift 1  ;;
        -d|--download)  export  FORCE_DOWNLOAD="$1";      shift 1  ;;
               --from)  export  SOURCE_CACHE=$2;          shift 2  ;;
@@ -655,14 +629,17 @@ function strip_parameters()  {
 function acquire_cast_lock() {
   # locking - blocks normal spells if a solo cast is running,
   # solo casts if any cast is running
-  message "Waiting for any ${FILE_COLOR}Solo${DEFAULT_COLOR} casts to complete..."
+  message "Waiting for any ${FILE_COLOR}Solo${DEFAULT_COLOR}" \
+          "casts to complete..."
   lock_resources "solo" "cast"
   if grep -q "^$SPELL$" $SOLO || [ -f $SCRIPT_DIRECTORY/SOLO ]
   then #SOLO spell
-    message -n "Waiting for ${SPELL_COLOR}all other${DEFAULT_COLOR} spells to complete..."
+    message -n "Waiting for ${SPELL_COLOR}all other${DEFAULT_COLOR}" \
+               "spells to complete..."
     excllock_resources "cast" "$SPELL"
   else
-    message -n "Waiting for any other casts of ${SPELL_COLOR}$SPELL${DEFAULT_COLOR} to complete..."
+    message -n "Waiting for any other casts of" \
+               "${SPELL_COLOR}$SPELL${DEFAULT_COLOR} to complete..."
     lock_resources "cast" "$SPELL"
     unlock_resources "solo" "cast"
   fi
@@ -687,19 +664,11 @@ function cast_spell()  { (
   run_security  &&
   run_conflicts &&
 
-  # this is already done by run_details, and should go away (afk 4/10/04)
-  run_spell_config                            &&
-
-  # depends should not be an issue here, the whole point of using make
-  # was to avoid having to care at this point
-  # this line may disappear (afk 4/10/04)
-  satisfy_depends             && #needed or optional deps dont get passed??
-  show_downloading            && 
-  verify_sources              ||   return 1
+  show_downloading $SPELL
+  verify_sources ||   return 1
   
   # wait for solo casts, to finish and ensure that others can't
   acquire_cast_lock
-
 
   # all this needs to reorganized and stuff...later
 
@@ -712,7 +681,15 @@ function cast_spell()  { (
 
 
   #some minor discussion occured about having this, i'll leave it out for now
-  #activity_log  "cast"  "$SPELL"  "$VERSION"  "start"
+  activity_log  "cast"  "$SPELL"  "$VERSION"  "start"
+
+  run_spell_config                            
+
+  # this should probably be moved...
+  spell_depends=$(hash_get uncommitted_hash $SPELL)
+  local OPTS
+  test -e $spell_depends && 
+  OPTS="$OPTS $(get_depends_options $spell_depends $SPELL)"
   
   # this will run through the whole build process
   run_build_spell
@@ -721,23 +698,16 @@ function cast_spell()  { (
   # This is the home for anything and everything we do
   # when a phase4 succeeds or fails, no more spreading things out
   # into multiple functions.
-  cd /
 
+  cd /
 
   pop_install_queue "$SPELL"    
 
   # hooks back out to the build_api to do whatever needs to be done
   if [ $rc == 0 ] ; then
-    create_compile_log
     run_spell_success
-    CAST_EXIT_STATUS=0
   else
-    if [ $rc != 1 ] ; then # dont munge the log if pre_build failed
-      create_compile_log
-      view_compile_log
-    fi
-    run_spell_failure
-    CAST_EXIT_STATUS=$rc
+    run_spell_failure $rc
   fi
 
 
@@ -745,7 +715,7 @@ function cast_spell()  { (
   #It's OK to try to release a lock you don't have
   unlock_resources "solo" "cast"
 
-  return $CAST_EXIT_STATUS
+  return $rc
 
 ) }
 
@@ -762,35 +732,6 @@ function current_sources()  {
 
   spell_installed  $SPELL  &&
   [  "$VERSION"  ==  "`installed_version  $SPELL`"  ]
-
-}
-
-#---------------------------------------------------------------------
-## @Globals D_LOG COMPILE FORCE_COMPILE SPELL
-## Downloads the sources by calling summon if it has to.
-## It downloads if COMPILE || FORCE_COMPILE || ! current_sources
-## || ! (spell_installed $SPELL || spell_held $SPELL)
-## It logs the download-process in D_LOG
-## Always touches ${D_LOG}.done.$SPELL at the end to signal that
-## it is done.
-#---------------------------------------------------------------------
-function run_summon()  {
-
-  touch $D_LOG
-  if 	[[ $COMPILE ]] 			|| 
-  		[[ $FORCE_COMPILE ]] 	|| 
-		! current_sources 		|| 
-		! (spell_installed $SPELL || spell_held $SPELL) 
-  then
-    lock_file   $D_LOG
-    
-    ( . summon  $SPELL  >>  $D_LOG  2>&1 )
-    
-    unlock_file $D_LOG
-  fi
-  
-  #This is to notify show_downloading that it is done this source
-  touch "${D_LOG}.done.$SPELL"
 
 }
 
@@ -813,7 +754,7 @@ function pass_one()  {
   echo -n "Computing previously installed dependencies..."
   compute_installed_depends "already_cast"
   echo
-  compute_uninstalled_depends "to_cast" "bad_cast" $SPELLS
+  compute_uninstalled_depends "to_cast" "back_hash" "bad_spells" $SPELLS
 
   message "${MESSAGE_COLOR}Collating dependencies...${DEFAULT_COLOR}"
   depends_to_Makefile to_cast already_cast > $MAKEFILE
@@ -859,32 +800,23 @@ function depends_to_Makefile()
 		echo
 	done
 	local all_spells=$({ hash_get_table_fields $1 ; hash_get_table_fields $2; } | tr '[:cntrl:]' ' ')
+        # make will run the all target, which would be the spells we care about
 	echo "all : $all_spells"
+        echo
+        # if dependency rules fail us, match here after everything else
+	# has had the chance, and do nothing, instead of exit early...
+        echo %:
+	echo -e "\t@echo -n"
 	echo
+        # this caused a rather nasty bug where a file in the current directory
+	# had the same name as a spell, and make thought it had already "made"
+	# that spell
 	echo ".PHONY : all $all_spells"
 
 #	export SPELLS="$all_spells"
 	
 }
 
-
-#---------------------------------------------------------------------
-## @Globals SPELLS
-## @Arguments spellname
-## calls run_details and run_summon for every element in SPELLS
-## doesn't actually build anything, just summons it.
-#---------------------------------------------------------------------
-function build_sources()  {
-
-  for  SPELL  in  $SPELLS;  do
-    ( run_details                       &&
-#      satisfy_depends  && (duff, probably not needed 10/07)
-      run_summon
-      debug "cast" "Out of run_summon."
-    )
-  done
-
-}
 
 #---------------------------------------------------------------------
 ## @Arguments Spells to be cast
@@ -929,14 +861,22 @@ function pass_two()  {
 #---------------------------------------------------------------------
 ## @param spellname
 ## @Globals SPELL
-## Sets SPELL to the spellname and calls build_sources with spellname
-## as argument.
+## Sets SPELL to the spellname and calls summon_spells with spellname
+## as argument. This is equivalent to calling summon, but without the
+## overhead.
 ## (Is being called by make)
 #---------------------------------------------------------------------
 function pass_three()  {
   debug "cast" "pass_three - $*"
-  SPELL=$1
-  build_sources $*
+  local SPELL=$1
+  local download_log=$(get_spell_dl_log $SPELL)
+  touch $download_log
+  lock_file   $download_log
+  summon_spells "$SPELL"  >>  $download_log  2>&1 
+  unlock_file   $download_log
+  
+  #This is to notify show_downloading that it is done this source
+  touch "${download_log}.done"
 }
 
 #---------------------------------------------------------------------
@@ -1029,19 +969,15 @@ function pass_five()  {
 
 #---------------------------------------------------------------------
 ## @Arguments Spells to cast
-## @Globals CAST_PASS D_LOG 
+## @Globals CAST_PASS
 ## 
 ## Starts the passes and sets CAST_PASS accordingly.
-## D_LOG is being set and the file is being cleared if it does already
-## exists 
 #---------------------------------------------------------------------
 function pass_zero()  {
 
   debug "cast" "Starting pass_zero()"
   PASS_ZERO="y"  #<--- What is this here for? (Duff, 03/02/13)
-  export  D_LOG="/tmp/sorcery/cast/$$/downloading.$RANDOM"
-  rm -f $D_LOG 2>/dev/null
-
+                 # grep says that its used in run_fix (afk, June 04)
   debug "pass_zero" "Starting passes 1,2,3,4 with : '$*'"
   debug "pass_zero" "   and with spells : '$SPELLS'"
   export  CAST_PASS="one";    pass_one $*  &&
@@ -1050,8 +986,6 @@ function pass_zero()  {
   debug "pass_zero" "Starting pass 5 with: '$@'"
   export  CAST_PASS="five";  pass_five "$@"
 
-  rm  -f   $D_LOG*
-  
 
 }
 
@@ -1070,26 +1004,27 @@ function int_trap()
 #---------------------------------------------------------------------
 ## @Globals RM_AT_END
 ## RM_AT_END is being set in main.
-## Used for cleaning up. Deleting some files and /tmp/sorcery/cast/$$
-## basically.
+## Used for cleaning up. Deleting some files and $TMP_DIR.
 #---------------------------------------------------------------------
 function cleanup() {
-  
   debug "cleanup" "Cleaning up the contents of `cat $RM_AT_END 2>/dev/null`"
   rm $(cat $RM_AT_END 2>/dev/null) $RM_AT_END 2>/dev/null
-  rm -rf /tmp/sorcery/cast/$$
-
+  rm -rf $TMP_DIR
 }
 #---------------------------------------------------------------------
-## Safely creates /tmp/sorcery/cast/$$
+## Safely creates $TMP_DIR and exports the variable so we can use it
+## even in subprocesses called through make.
 #---------------------------------------------------------------------
 function mk_tmp_dirs() {
-	debug "$FUNCNAME" "Making tmp dirs for $$"
-	if [ -d /tmp/sorcery/cast/$$ ] ; then
-		echo "Looks like you had an old cast on PID $$. I'm cleaning it out."
-		rm -rf /tmp/sorcery/cast/$$
-	fi
-	mkdir -p /tmp/sorcery/cast/$$
+  debug "$FUNCNAME" "Making tmp dirs for $$"
+  # in order for TMP_DIR to make it through make and into pass_three/four
+  # we must export
+  export TMP_DIR=/tmp/sorcery/cast/$$
+  if [ -d $TMP_DIR ] ; then
+    echo "Looks like you had an old cast on PID $$. I'm cleaning it out."
+    rm -rf $TMP_DIR
+  fi
+  mkdir -p $TMP_DIR
 }
 
 #---------------------------------------------------------------------
@@ -1103,37 +1038,6 @@ function mk_tmp_dirs() {
 ## according to CAST_PASS
 #---------------------------------------------------------------------
 function main()	{
-
-  # TEMPORARY HACK!!
-  if ! [ -f /tmp/sorcery/cast_ran_cleanse ] ; then
-  	[ -d /tmp/sorcery ] || mkdir -p /tmp/sorcery
-  	touch /tmp/sorcery/cast_ran_cleanse 
-  	message "Due to some internal changes, it is likely that"
-	message "a new script called ${WHITE}cleanse${DEFAULT_COLOR} must be run at "
-	message "least once on your system. A file has been created"
-	message "called /tmp/sorcery/cast_ran_cleanse. So long as "
-	message "the file is there, this step will be skipped in "
-	message "future casts."
-	message
-	message "If cast exits after some errors about not being "
-	message "able to find targets and being unable to make all"
-	message "please run cleanse again and make sure that it "
-	message "completes without complaint."
-	message
-	message "${BOLD}You may at this point want to ^C and run cleanse "
-	message "yourself manualy. This is safer but requires you"
-	message "to perform some commands manualy at the end.${DEFAULT}"
-	message 
-	echo -en "\a" ; sleep 4
-	echo -en "\a" ; sleep 3
-	echo -en "\a" ; sleep 2
-	echo -en "\a" ; sleep 1
-	message -n "Press enter to continue and run cleanse..."
-	read LINE
-	message "Running cleanse..."
-	cleanse --packages --delint --prune doit
-  fi
-  # END OF TEMPORARY HACK!!
 
   debug "cast" "main() - $*"
   local T_SPELLS=""
@@ -1158,8 +1062,8 @@ function main()	{
 		  return 1
 	  fi
 	
-	  MAKEFILE="/tmp/sorcery/cast/$$/Makefile"
-	  export ENV_CACHE=${ENV_CACHE:-/tmp/sorcery/cast/$$/envCache}
+	  MAKEFILE="$TMP_DIR/Makefile"
+	  export ENV_CACHE=${ENV_CACHE:-$TMP_DIR/envCache}
 	  echo "$SUCCESS_LIST $FAILED_LIST $0 $ENV_CACHE" >> $RM_AT_END
 	  export RM_AT_END="$RM_AT_END"
 	  BASE_SPELLS=" $SPELLS "
@@ -1182,6 +1086,7 @@ function main()	{
 
 
 . /etc/sorcery/config
+export TOP_LEVEL=${TOP_LEVEL:-$SHLVL}
 
 if    [  $#      -eq  0  ];  then  help  |  $PAGER
 
@@ -1198,16 +1103,17 @@ elif  [  ${0:0:5} !=  "/tmp/"  ];  then
 
   if ! [[ $RM_AT_END ]] ; then
     #This stuff is here to make sure a user can't make the file
-	  # and fill it up with stuff the feel the need to delete
-    export RM_AT_END=${RM_AT_END:-"/tmp/sorcery/cast/$$/tmplist"}
-	  touch $RM_AT_END
-	  chown root:root $RM_AT_END
-	  echo -n '' > $RM_AT_END
+    # and fill it up with stuff we feel the need to delete
+    export RM_AT_END=${RM_AT_END:-"$TMP_DIR/tmplist"}
+    touch $RM_AT_END
+    chown root:root $RM_AT_END
+    chmod 600 $RM_AT_END
+    echo -n '' > $RM_AT_END
   fi
   
-  export SAFE_CAST=/tmp/sorcery/cast/$$/casting.safe
-  export SUCCESS_LIST="/tmp/sorcery/cast/$$/success_list"
-  export FAILED_LIST="/tmp/sorcery/cast/$$/failed_list"
+  export SAFE_CAST=$TMP_DIR/casting.safe
+  export SUCCESS_LIST="$TMP_DIR/success_list"
+  export FAILED_LIST="$TMP_DIR/failed_list"
   lock_file $SAFE_CAST
   
   cp  $0  $SAFE_CAST
@@ -1216,17 +1122,14 @@ elif  [  ${0:0:5} !=  "/tmp/"  ];  then
   exec $SAFE_CAST "$@"
   
 else
-
   if  [[  $NICE != "0"  ]] ; then
     renice $NICE -p $$  >/dev/null
   fi
   trap int_trap INT
   main  $*
-  if [ $SHLVL -eq 2 ] ; then
-	unlock_file $SAFE_CAST
-	cleanup
-  else
-  	rm -rf /tmp/sorcery/cast/$$
+  if [ $SHLVL -eq $TOP_LEVEL ] ; then
+    unlock_file $SAFE_CAST
+    cleanup
   fi
 
 fi
