Release 1.4

diff --git a/usr/sbin/cast b/usr/sbin/cast
--- a/usr/sbin/cast
+++ b/usr/sbin/cast
@@ -23,7 +23,7 @@
 #---------------------------------------------------------------------
 
 
-help()	{
+function help()	{
 
   cat  <<  EOF
 
@@ -64,7 +64,7 @@ EOF
 }
 
 
-set_failed_cast() {
+function set_failed_cast() {
   if [[ $FAILED_CASTS ]] ; then
     FAILED_CASTS="$FAILED_CASTS $SPELL"
   else
@@ -72,7 +72,7 @@ set_failed_cast() {
   fi
 }
 
-set_successful_cast() {
+function set_successful_cast() {
   if [[ $SUCCESSFUL_CASTS ]] ; then
     SUCCESSFUL_CASTS="$SUCCESSFUL_CASTS $SPELL"
   else
@@ -80,7 +80,7 @@ set_successful_cast() {
   fi
 }
 
- run_conflicts() {
+function run_conflicts() {
     
      debug "cast" "Starting run_conflicts() on $SPELL"
     local CONFLICTS
@@ -99,7 +99,7 @@ set_successful_cast() {
 
 # checks for a security file
 # returns 0 if spell should be cast, 1 otherwise
-run_security() {
+function run_security() {
     debug "cast" "Starting run_security() on $SPELL"
     if    [  -f  $SCRIPT_DIRECTORY/SECURITY  ]; then
       echo -e "${SPELL_COLOR}${SPELL}:${DEFAULT_COLOR}"
@@ -120,7 +120,7 @@ run_security() {
 }
 
 
-prepare_spell_config()  {
+function prepare_spell_config()  {
 
   SPELL_CONFIG=$DEPENDS_CONFIG/$SPELL
   if  !  [  -x  $SPELL_CONFIG  ];  then
@@ -133,7 +133,7 @@ prepare_spell_config()  {
 }
 
 
-use_xinetd()  { (
+function use_xinetd()  { (
 
   if  [  -d  $SCRIPT_DIRECTORY/xinetd.d  ]  &&
       !  grep  -q  "SERVICES="  $SPELL_CONFIG
@@ -172,7 +172,7 @@ use_xinetd()  { (
 ) }
 
 # Automagic initscript installation.
-use_initd()  { (
+function use_initd()  { (
 
   debug "cast" "In use_initd()"
 
@@ -209,7 +209,7 @@ use_initd()  { (
 ) }
 
 
-run_pre_build() {
+function run_pre_build() {
 
   debug "cast" "run_pre_build()"
   message  "${MESSAGE_COLOR}Building"  \
@@ -229,7 +229,7 @@ run_pre_build() {
 }
 
 
-create_compile_log()  {
+function create_compile_log()  {
 
   message  "${MESSAGE_COLOR}Creating"                        \
            "${FILE_COLOR}$COMPILE_LOGS/$SPELL-$VERSION.bz2"  \
@@ -242,7 +242,7 @@ create_compile_log()  {
 }
 
 
-view_compile_log()  {
+function view_compile_log()  {
 
     sleep   1
     report              $C_LOG  "Compile log"
@@ -250,7 +250,7 @@ view_compile_log()  {
 }
 
 
-activate_voyeur()  {
+function activate_voyeur()  {
 
   if  [  -z  "$SILENT"  ];  then
     case  $VOYEUR  in
@@ -263,7 +263,7 @@ activate_voyeur()  {
 }
 
 
-run_build()  {
+function run_build()  {
 
   debug "cast" "Starting run_build()"
    C_LOG=/tmp/$SPELL.compile.log
@@ -304,7 +304,7 @@ run_build()  {
       # load custom OPTS
       if  [  -f $SM_CONFIG_OPTION_CACHE/$SPELL  ];  then
         OPTS="$OPTS $(cat $SM_CONFIG_OPTION_CACHE/$SPELL)"
-        message "${MESSAGE_COLOR} OPTS= ${SPELL_COLOR}$OPTS"
+        message "${MESSAGE_COLOR} OPTS= ${DEFAULT_COLOR}$OPTS"
       fi
     fi
   fi
@@ -330,7 +330,7 @@ run_build()  {
 }
 
 
-run_post_build() {
+function run_post_build() {
 
   if  [  -x  $SCRIPT_DIRECTORY/POST_BUILD  ];  then
            . $SCRIPT_DIRECTORY/POST_BUILD
@@ -338,10 +338,13 @@ run_post_build() {
     default_post_build
   fi
 
+  # Lock made in prepare_install
+  unlock_resources "libgrimoire" "install"
+
 }
 
 
-run_post_install() {
+function run_post_install() {
 
   if    [  -x  $SCRIPT_DIRECTORY/POST_INSTALL  ]
   then       . $SCRIPT_DIRECTORY/POST_INSTALL
@@ -354,7 +357,7 @@ run_post_install() {
 }
 
 
-lib_dirs()  {
+function lib_dirs()  {
 
   for  DIRECTORY  in  $*;  do
     for FILE in $DIRECTORY/*.so* ; do
@@ -368,7 +371,7 @@ lib_dirs()  {
 }
 
 
-export_ld()  {
+function export_ld()  {
 
   if    [  -z  "$LD_LIBRARY_PATH"  ] ; 
   then  export   LD_LIBRARY_PATH="$( lib_dirs  $*  )"
@@ -381,7 +384,7 @@ export_ld()  {
 }
 
 
-ldd_check()  {  (
+function ldd_check()  {  (
 
   if  [  "$LDD_CHECK"  ==  "off"    ] ;  then
     return
@@ -437,7 +440,7 @@ ldd_check()  {  (
 ) }
 
 
-find_check()  { (
+function find_check()  { (
 
   if  [  "$FIND_CHECK"  ==  "off"             ]   ||
       [  "$1"           ==  "xfree86"         ]   ||
@@ -498,7 +501,7 @@ find_check()  { (
 ) }
 
 
-show_owner()  {
+function show_owner()  {
 
   OWNER=`grep  $TARGET  $INSTALL_LOGS/*  |
          cut  -d :  -f1                  |
@@ -511,7 +514,7 @@ show_owner()  {
 }
 
 
-remove_line()  {
+function remove_line()  {
 
   F_TMP=/tmp/`basename  $I_LOG`.$$.$RANDOM
 
@@ -531,7 +534,7 @@ remove_line()  {
 }
 
 
-sym_check()  { (
+function sym_check()  { (
 
   if  [  "$SYM_CHECK"  ==  "off"  ];  then
     return
@@ -650,7 +653,7 @@ md5sum_check()  { (
 ) }
 
 
-status_okay()  {
+function status_okay()  {
 
   spell_installed  $1  ||
   spell_held       $1
@@ -658,7 +661,7 @@ status_okay()  {
 }
 
 
-run_checks()  {
+function run_checks()  {
 
   if  [ -z  "$QUIET"  ]; then
     progress_bar $DOT_PROGRESS 1 1 50 
@@ -673,7 +676,7 @@ run_checks()  {
 }
 
 
-run_fix()  { (
+function run_fix()  { (
 
   SPELLS=$*
 
@@ -794,7 +797,7 @@ run_fix()  { (
 ) }
 
 
-process_parameters()  {
+function process_parameters()  {
 
   while  [  -n  "$1"  ];  do
 
@@ -845,7 +848,7 @@ process_parameters()  {
 }
 
 
-strip_parameters()  {
+function strip_parameters()  {
 
   while  [  -n  "$1"  ];  do
 
@@ -880,13 +883,13 @@ strip_parameters()  {
 
 }
 
-can_resurect()  {
+function can_resurect()  {
 	debug "cast" "can_resurect - $*"
 	run_details		&&
 	[ -f $INSTALL_CACHE/$SPELL-$VERSION-$BUILD.tar.bz2 ] &&
 	debug "cast" "I am able to resurect."
 }
-resurrect()  {  (  
+function resurrect()  {  (  
 
   debug "cast" "resurect - $*"
 
@@ -929,7 +932,7 @@ resurrect()  {  (
 )  }
 
 
-show_download_progress()  {
+function show_download_progress()  {
 
   if  [  -f  "$D_LOG"   ]   &&
       [  -z  "$SILENT"  ];  then
@@ -949,7 +952,7 @@ show_download_progress()  {
 }
 
 
-show_downloading()  {
+function show_downloading()  {
 
 #  COMPILE="y"
   debug "cast" "Started show_downloading() on $SPELL"
@@ -971,7 +974,7 @@ show_downloading()  {
 }
 
 
-report_install()  {
+function report_install()  {
 
 #  rm  -f  $BOOST_LOCK
   INST_LOG=$INSTALL_LOGS/$SPELL-$VERSION
@@ -982,7 +985,7 @@ report_install()  {
 
 
 
-cast_spell()  { (
+function cast_spell()  { (
 
   debug "cast" "Casting spell [$SPELL]"
   run_details                                 && #run by can_resurect now, but it's a minor expense
@@ -1020,6 +1023,9 @@ cast_spell()  { (
 	    rm_source_dir
 		echo $SPELL >> $SUCCESS_LIST
   else
+    # This may have been locked if there was a failure during the install
+    unlock_resources "libgrimoire" "install"
+	
     activity_log "cast" "$SPELL"  "$VERSION" "failure"
 	IW_LOG="$INSTALLWATCHFILE"
 	INSTALLWATCHFILE=""
@@ -1038,7 +1044,7 @@ cast_spell()  { (
 
 ##Removed *_solo functions, Duff 2002/11/01
 
-current_sources()  {
+function current_sources()  {
 
   spell_installed  $SPELL  &&
   [  "$VERSION"  ==  "`installed_version  $SPELL`"  ]
@@ -1046,8 +1052,9 @@ current_sources()  {
 }
 
 
-run_summon()  {
-  
+function run_summon()  {
+
+  touch $D_LOG
   if 	[[ $COMPILE ]] 			|| 
   		[[ $FORCE_COMPILE ]] 	|| 
 		! current_sources 		|| 
@@ -1065,7 +1072,7 @@ run_summon()  {
 
 }
 
-pass_one()  {
+function pass_one()  {
   #  This pass does configuration and dependency identification.
   debug "cast" "Starting pass_one()"
 
@@ -1131,7 +1138,7 @@ function depends_to_Makefile()
 
 
 #A bit of a misnomer, eh? Doesn't build anything, just summons it.
-build_sources()  {
+function build_sources()  {
 
   for  SPELL  in  $SPELLS;  do
     ( run_details                       &&
@@ -1173,13 +1180,13 @@ function pass_two()  {
 
 }
 
-pass_three()  {
+function pass_three()  {
   debug "cast" "pass_three - $*"
   SPELL=$1
   build_sources $*
 }
 
-pass_four()  {
+function pass_four()  {
 
   debug "cast" "pass_four - $*"
   SPELL=$1
@@ -1197,7 +1204,7 @@ pass_four()  {
 
 
 # Report generation
-pass_five()  {
+function pass_five()  {
 
   local SOME_CAST_FAILED=""
   
@@ -1227,7 +1234,7 @@ pass_five()  {
 
 }
 
-pass_zero()  {
+function pass_zero()  {
 
   debug "cast" "Starting pass_zero()"
   PASS_ZERO="y"  #<--- What is this here for? (Duff, 03/02/13)
@@ -1244,8 +1251,19 @@ pass_zero()  {
 
 }
 
+function int_trap()
+{
+	message "${PROBLEM_COLOR}SIGINT${DEFAULT_COLOR}"
+	message "Cleaning up as well as I can..."
+	cleanup
+	exit 1
+}
 
-main()	{
+function cleanup() {
+	rm $(cat $RM_AT_END 2>/dev/null) $RM_AT_END 2>/dev/null
+}
+
+function main()	{
   debug "cast" "main() - $*"
   local T_SPELLS=""
   process_parameters        $*
@@ -1323,10 +1341,11 @@ elif  [  "$(  dirname  $0  )"  !=  "/tmp"  ];  then
 else
 
   renice +10 -p $$  >/dev/null
+  trap int_trap INT
   main  $*
   if [ $SHLVL -eq 2 ] ; then
 	unlock_file $SAFE_CAST
-	rm $(cat $RM_AT_END) $RM_AT_END 2>/dev/null
+	cleanup
   fi
 
 fi
