scribe support for CROSS_INSTALL INSTALL_ROOT libcrossinstall now makes a mail dir /var/spool/mail also

diff --git a/usr/sbin/scribe b/usr/sbin/scribe
--- a/usr/sbin/scribe
+++ b/usr/sbin/scribe
@@ -191,13 +191,13 @@ for  ((x=0; x <= $i_count-1; x++))
 
  echo "Adding grimoire ${ITEMS[$x]} from $FROM_LOC"
 
- if ! [ -d $CODEX_ROOT ] ; then
-   echo "Main codex directory not present. Createing $CODEX_ROOT."
-   mkdirheir $CODEX_ROOT
+ if ! [ -d $INSTALL_ROOT$CODEX_ROOT ] ; then
+   echo "Main codex directory not present. Creating $INSTALL_ROOT$CODEX_ROOT."
+   mkdir -p $INSTALL_ROOT$CODEX_ROOT
  fi
 
  #switch to and work in the codex
- pushd $CODEX_ROOT > /dev/null
+ pushd $INSTALL_ROOT$CODEX_ROOT > /dev/null
 
  #download the grimoire using subroutines
  NO_FUZZ=on
@@ -222,15 +222,15 @@ for  ((x=0; x <= $i_count-1; x++))
    fi
 
    #make sure that it untarred to the proper dir.
-   if [ -d $CODEX_ROOT/${ITEMS[$x]} ]; then
+   if [ -d $INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]} ]; then
 
-        GRIMOIRE_TMP="$CODEX_ROOT/${ITEMS[$x]}"
+        GRIMOIRE_TMP="$INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]}"
 
    else
 
-     if  [ -d $CODEX_ROOT/grimoire ]; then
-        mv -f $CODEX_ROOT/grimoire $CODEX_ROOT/${ITEMS[$x]}
-        GRIMOIRE_TMP="$CODEX_ROOT/${ITEMS[$x]}"
+     if  [ -d $INSTALL_ROOT$CODEX_ROOT/grimoire ]; then
+        mv -f $INSTALL_ROOT$CODEX_ROOT/grimoire $INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]}
+        GRIMOIRE_TMP="$INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]}"
 
      fi
 
@@ -245,13 +245,13 @@ for  ((x=0; x <= $i_count-1; x++))
        #check if we are dealing with a base grimoire
        if [ -e $GRIMOIRE_TMP/BASE ]; then
               OLD_BASE=`ls -l base-grimoire | awk '{print $NF}'`
-                   rm -f $CODEX_ROOT/base-grimoire
-              ln -s $GRIMOIRE_TMP $CODEX_ROOT/base-grimoire 
+                   rm -f $INSTALL_ROOT$CODEX_ROOT/base-grimoire
+              ln -s $GRIMOIRE_TMP $INSTALL_ROOT$CODEX_ROOT/base-grimoire 
        fi
         
-       codex_add_grimoire $CODEX_ROOT/${ITEMS[$x]} 0
+       codex_add_grimoire \${INSTALL_ROOT}$CODEX_ROOT/${ITEMS[$x]} 0
 
-       codex_create_cache $CODEX_ROOT/${ITEMS[$x]}
+       codex_create_cache ${INSTALL_ROOT}$CODEX_ROOT/${ITEMS[$x]}
        
        echo "Grimoire \"${ITEMS[$x]}\" successfully added to your codex." 
    else
@@ -293,16 +293,16 @@ do
  fi
 
  #if the grimoire exists, remove it
- if [ -d $CODEX_ROOT/${ITEMS[$x]} ]; then
+ if [ -d $INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]} ]; then
 
   #found. removed.
-  rm -rf $CODEX_ROOT/${ITEMS[$x]}
+  rm -rf $INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]}
   echo "Removing grimoire ${ITEMS[$x]} from codex"
-  codex_remove_grimoire $CODEX_ROOT/${ITEMS[$x]}
+  codex_remove_grimoire $INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]}
  else
 
   #not found - print error
-  echo "Grimoire ${ITEMS[$x]} does not exist in $CODEX_ROOT. No action."
+  echo "Grimoire ${ITEMS[$x]} does not exist in $INSTALL_ROOT$CODEX_ROOT. No action."
 
  fi
 
@@ -332,7 +332,7 @@ if  query "Repair Grimoire:$1's Metadata?" n; then
 
     echo "Setting Metadata to: $URL"
     echo "If this is incorrect, run \"scribe fix $1\" and correct"
-    GRIMOIRE_TMP=$CODEX_ROOT/$1
+    GRIMOIRE_TMP=$INSTALL_ROOT$CODEX_ROOT/$1
     echo "FROM_URL=$URL" > $GRIMOIRE_TMP/GRIMOIRE
     chmod +x $GRIMOIRE_TMP/GRIMOIRE
     return 0
@@ -346,7 +346,7 @@ fix() {
 
 for i in "${ITEMS[@]}"; do
 
-  if ! [ -e $CODEX_ROOT/$i/GRIMOIRE ]; then
+  if ! [ -e $INSTALL_ROOT$CODEX_ROOT/$i/GRIMOIRE ]; then
 
     if fix_metadata $i; then
      echo "$i fixed."
@@ -386,7 +386,7 @@ done
 do_update() {
 
           #switch to codex for update
-          pushd $CODEX_ROOT
+          pushd $INSTALL_ROOT$CODEX_ROOT
  
           #download updated grimoire without fuzzy
           NO_FUZZ=on
@@ -414,18 +414,17 @@ do_update() {
             fi
 
               #check for a successful unzip
-              if [ -d $CODEX_ROOT/$1 ]; then
+              if [ -d $INSTALL_ROOT$CODEX_ROOT/$1 ]; then
 
                   #success! create metadata
-                  echo "FROM_URL=$2" > $CODEX_ROOT/$1/GRIMOIRE
-                  chmod +x $CODEX_ROOT/$1/GRIMOIRE
+                  echo "FROM_URL=$2" > $INSTALL_ROOT$CODEX_ROOT/$1/GRIMOIRE
+                  chmod +x $INSTALL_ROOT$CODEX_ROOT/$1/GRIMOIRE
                   
                   #check if base grimoire
-                  if [ -e $CODEX_ROOT/$1/BASE ]; then
+                  if [ -e $INSTALL_ROOT$CODEX_ROOT/$1/BASE ]; then
                       OLD_BASE=`ls -l base-grimoire | awk '{print $NF}'`
-                      rm -f $CODEX_ROOT/base-grimoire
-                      ln -s $CODEX_ROOT/$1 $CODEX_ROOT/base-grimoire 
-
+                      rm -f $INSTALL_ROOT$CODEX_ROOT/base-grimoire
+                      ln -s $INSTALL_ROOT$CODEX_ROOT/$1 $INSTALL_ROOT$CODEX_ROOT/base-grimoire 
                   fi
 
                   #and remove backup version
@@ -435,7 +434,7 @@ do_update() {
                   
                   #Confirm Success!
                   echo "$1 Updated!"
-                  grimoire_history $CODEX_ROOT/$1
+                  grimoire_history $INSTALL_ROOT$CODEX_ROOT/$1
 
               else
 
@@ -479,10 +478,10 @@ if [ $i_count == 0 ]; then
      i=`basename "$j"`
         
         #if it exists and has metadata
-        if [ -e $CODEX_ROOT/$i/GRIMOIRE ] || fix_metadata $i; then
+        if [ -e $INSTALL_ROOT$CODEX_ROOT/$i/GRIMOIRE ] || fix_metadata $i; then
             
             #include metadata
-            . $CODEX_ROOT/$i/GRIMOIRE
+            . $INSTALL_ROOT$CODEX_ROOT/$i/GRIMOIRE
             FROM_LOC=$FROM_URL
             echo "Updating grimoire $i from $FROM_LOC"
             do_update $i $FROM_LOC
@@ -502,7 +501,7 @@ else
       do
       
       #if the codex exists
-      if [ -d $CODEX_ROOT/${ITEMS[$x]} ]; then
+      if [ -d $INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]} ]; then
           
           #if a FROM is given, check its validity
           if [ -n "${SOURCES[$x]}" ]; then
@@ -515,8 +514,8 @@ else
               else
                   
                   #invalid FROM. Use metadata instead.
-                  if [ -e $CODEX_ROOT/${ITEMS[$x]}/GRIMOIRE ] || fix_metadata ${ITEMS[$x]}; then
-                          . $CODEX_ROOT/${ITEMS[$x]}/GRIMOIRE
+                  if [ -e $INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]}/GRIMOIRE ] || fix_metadata ${ITEMS[$x]}; then
+                          . $INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]}/GRIMOIRE
                           FROM_LOC=$FROM_URL
                           echo "Error: ${SOURCES[$x]} is not a valid URL. Using: $FROM_LOC"
                   else
@@ -526,8 +525,8 @@ else
           else
 
               #no FROM given. Use metadata.
-                  if [ -e $CODEX_ROOT/${ITEMS[$x]}/GRIMOIRE ] || fix_metadata ${ITEMS[$x]}; then
-                          . $CODEX_ROOT/${ITEMS[$x]}/GRIMOIRE
+                  if [ -e $INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]}/GRIMOIRE ] || fix_metadata ${ITEMS[$x]}; then
+                          . $INSTALL_ROOT$CODEX_ROOT/${ITEMS[$x]}/GRIMOIRE
                           FROM_LOC=$FROM_URL
                   else
                           echo "${ITEMS[$x]} has invalid metadata. Not Updated"
@@ -540,7 +539,7 @@ else
       else
 
           #the grimoire doesnt exist to update!
-          echo "Grimoire ${ITEMS[$x]} not found in $CODEX_ROOT"
+          echo "Grimoire ${ITEMS[$x]} not found in $INSTALL_ROOT$CODEX_ROOT"
       
       fi
 
