Huge stable update. This brings stable up to test/...@2004/03/03 with a few omissions.

diff --git a/usr/sbin/scribe b/usr/sbin/scribe
--- a/usr/sbin/scribe
+++ b/usr/sbin/scribe
@@ -25,6 +25,8 @@ Scribe is a utility for controlling the grimoires in your codex,
 and the spells in your grimoires.
 
 Usage:    scribe a[dd]|r[emove]|u[pdate]|f[ix] subject [[from] source locations]
+          scribe [re]index
+          scribe swap <grimoire1> <grimoire2>
 
 Optional Parameters:
 
@@ -199,14 +201,25 @@ for  ((x=0; x <= $i_count-1; x++))
 
  #download the grimoire using subroutines
  NO_FUZZ=on
+ url_set_options nocache
  url_download $FROM_LOC
 
  #check the success of the download
+ if [ $? != 0 ]; then
+
+   #grimoire was not downloaded. Error message.
+   echo "GRIMOIRE NOT FOUND"
+
+ else
+
+   #if the grimoire is an archive, untar it
  if [ -e ${ITEMS[$x]}.tar.bz2 ]; then
  
   #if successfuly downloaded, untar it and remove the zip
   bzcat ${ITEMS[$x]}.tar.bz2 | tar -x  1>/dev/null 2>&1 
   rm ${ITEMS[$x]}.tar.bz2
+
+   fi
 
    #make sure that it untarred to the proper dir.
    if [ -d $CODEX_ROOT/${ITEMS[$x]} ]; then
@@ -248,13 +261,8 @@ for  ((x=0; x <= $i_count-1; x++))
       echo "ERROR: Grimoire tarball for ${ITEMS[$x]} not formated correctly!"
 
    fi 
-  else
-   
-   #grimoire was not downloaded. Error message.
-   echo "GRIMOIRE NOT FOUND"
 
   fi
-
 #done. go back to directory being run from  
 popd >/dev/null
 
@@ -382,9 +390,18 @@ do_update() {
  
           #download updated grimoire without fuzzy
           NO_FUZZ=on
+          url_set_options nocache
           url_download $2
 
-          #if the download was successful continue
+          #check the success of the download
+          if [ $? != 0 ]; then
+
+            #grimiore download failed
+            echo "GRIMOIRE NOT FOUND AT SOURCE"
+
+          else
+
+            #if the grimoire is an archive, untar it
           if [ -e $1.tar.bz2 ]; then
 
               #backup old version until successful untar
@@ -393,6 +410,8 @@ do_update() {
               #untar the new grimoire update and remove zip
               bzcat $1.tar.bz2 | tar -x  1>/dev/null 2>&1 
               rm $1.tar.bz2
+
+            fi
 
               #check for a successful unzip
               if [ -d $CODEX_ROOT/$1 ]; then
@@ -410,10 +429,13 @@ do_update() {
                   fi
 
                   #and remove backup version
+              if [ -e temp_$1.old ]; then
                   rm -rf temp_$1.old
+              fi
                   
                   #Confirm Success!
                   echo "$1 Updated!"
+                  grimoire_history $CODEX_ROOT/$1
 
               else
 
@@ -424,11 +446,6 @@ do_update() {
                   mv -f temp_$1.old $1
               
               fi 
-          
-          else
-
-              #grimiore download failed
-              echo "GRIMOIRE NOT FOUND AT SOURCE"
           
           fi
           
diff --git a/var/lib/sorcery/modules/libdepends b/var/lib/sorcery/modules/libdepends
--- a/var/lib/sorcery/modules/libdepends
+++ b/var/lib/sorcery/modules/libdepends
@@ -33,7 +33,8 @@
 # PRETEND_NOT_INSTALLED: set here. It is a list of spells that are to be 
 #  recompiled, so they should not be treated as installed.
 
-function run_prepare() {
+function run_prepare() 
+{
 
   SCRIPT_DIRECTORY=`codex_find_spell_by_name $SPELL`
   debug "cast" "run_prepare() - SCRIPT_DIRECTORY = $SCRIPT_DIRECTORY"
@@ -47,19 +48,19 @@ function run_prepare() {
                "${SPELL_COLOR}${SPELL}"                   \
                "${DEFAULT_COLOR}"
   prepare_spell_config #from cast
-# Should this be here? It causes the questions to be asked twice - Chris 20030123
-#  use_xinetd #from cast
-#  use_initd
 
   if  [  -x  $SCRIPT_DIRECTORY/PREPARE  ];  then
     . $SCRIPT_DIRECTORY/PREPARE
   fi
-
+  
+  # ask the questions about xinetd/initd script installation
+  use_xinetd
+  use_initd
 }
 
 
-function run_depends()
-{ #SPELL=SPELL
+function run_depends() 
+{ 
  
   if  [  -x  $SCRIPT_DIRECTORY/DEPENDS  ];  then
 
@@ -70,32 +71,24 @@ function run_depends()
       .  $SCRIPT_DIRECTORY/DEPENDS
 
     fi
-
 }
 
 
-function run_configure() {
+function run_configure() 
+{
 
   SCRIPT_DIRECTORY=`codex_find_spell_by_name $SPELL`
   debug "cast" "run_configure() - SCRIPT_DIRECTORY = $SCRIPT_DIRECTORY"
  
-#  if  [  -n  "$RECONFIGURE"  ];  then
-#    rm  -f  $DEPENDS_CONFIG/$SPELL
-#    remove_depends_status  $SPELL
-#  fi
-
-#  prepare_spell_config  #This is also run in run_prepare. Shouldn't be needed here too.
-  use_xinetd
-  use_initd
-
   if  [  -x  $SCRIPT_DIRECTORY/CONFIGURE  ];  then
     . $SCRIPT_DIRECTORY/CONFIGURE
     true  # otherwise if CONFIGURE returns `false' DEPENDS is not executed
   fi
-
 }
 
-function run_spell_config() {
+
+function run_spell_config() 
+{
 
   SPELL_CONFIG=$DEPENDS_CONFIG/$SPELL
   debug "libdepends" "run_spell_config() - DEPENDS_CONFIG=$DEPENDS_CONFIG SPELL=$SPELL, SPELL_CONFIG=$SPELL_CONFIG DEPENDS_STATUS=$DEPENDS_STATUS" 
@@ -104,25 +97,28 @@ function run_spell_config() {
     debug "libdepends" "run_spell_config() - found $SPELL_CONFIG"
 	.  $SPELL_CONFIG
   fi
-  
 }
 
 
-function show_depends()  {
+function show_depends()  
+{
   debug "libdepends" "show_depends() - $@"
   local DEP_SPELL=`esc_str $1`
+  local DEPTH=$2
 
   if  !  echo  "$DONE"  |  grep  -q  "$DEP_SPELL";  then
     DONE="$DONE  $1"
 
     function ld99()  {
-      
+
+     [[ $MAX_DEPTH ]] && [[ $DEPTH -ge $MAX_DEPTH ]] && return 1
+ 
       SPELL=`echo  $1 |  cut  -d :  -f1`
       STATUS=`echo  $1  |  cut  -d :  -f3`
 
       if    [  "$STATUS"  ==  "on"  ]; then
-        echo          $1
-        show_depends  $SPELL
+        echo          $1 
+        show_depends  $SPELL $(( DEPTH + 1 ))
       fi
       
     }
@@ -130,7 +126,6 @@ function show_depends()  {
     iterate "ld99" $'\n' `grep  ":$DEP_SPELL:"  $DEPENDS_STATUS`
 
   fi
-
 }
 
 
@@ -157,11 +152,13 @@ function satisfy_depends()
     # First, see if the spell exists.
     DEP_SPELL_LOCATION=`codex_find_spell_by_name ${DEP[1]}`
     if  [  -z  "$DEP_SPELL_LOCATION"  ];  then
-      message  "${PROBLEM_COLOR}Unable to find previously configured"           \
-               "optional dependency ${SPELL_COLOR}'${DEP[1]}'${PROBLEM_COLOR}"
-      message  "in grimoire.  Removing spell from cached optional depends."     \
-               "${DEFAULT_COLOR}"
-      remove_depends_status  "$SPELL"  "${DEP[1]}"
+      if [  "${DEP[2]}"  !=  'providedby'  ]; then
+        message  "${PROBLEM_COLOR}Unable to find previously configured"  \
+                 "dependency ${SPELL_COLOR}'${DEP[1]}'${PROBLEM_COLOR}"
+        message  "in grimoire.  Removing spell from cached depends."     \
+                 "${DEFAULT_COLOR}"
+        remove_depends_status  "$SPELL"  "${DEP[1]}"
+      fi
     else
 
       #Second, am I trying to cast --fix or is this just a normal cast?
@@ -182,7 +179,7 @@ function satisfy_depends()
             !  spell_held       ${DEP[1]}
         then
           message "One of the dependancies of ${DEP[0]} failed to cast."
-	  message "You should try to cast ${DEP[1]} manualy."
+          message "You should try to cast ${DEP[1]} manualy."
           message "Failed to cast ${DEP[1]}. I will have trouble casting ${DEP[0]}."
           return 1          
         fi
@@ -201,15 +198,18 @@ function satisfy_depends()
   local OPTS_DEPENDS=$(get_depends_options "$SPELL")
   OPTS="$OPTS $OPTS_DEPENDS"
   debug 'libdepends' "satisfy_depends() - final OPTS=$OPTS"
-
 }
-function compute_depends()
-{ # $1=var to place spells in, $* = root spells
+
+
+function compute_depends() 
+{ 
+
+  # $1=var to place spells in, $* = root spells
 
   debug "libdepends" "compute_depends of $*"
   local outVar="$1"
   shift
-  BASE_SPELLS="$*"
+  BASE_SPELLS=( $@ )
   
   local i
   SPELLS=()
@@ -219,15 +219,12 @@ function compute_depends()
     let i++
   done
   
-  #PRETEND_NOT_INSTALLED assumes list is space separated
-#  if [[ $COMPILE ]] ; then
-#    PRETEND_NOT_INSTALLED=" ${SPELLS[*]} "
-#  else
-#    private_remove_installed_spells
-#  fi
-  
   for (( i=0 ; i<${#SPELLS[*]} ; i++ )) ; do
-    private_run_depends ${SPELLS[$i]}
+    if ! private_run_depends ${SPELLS[$i]} ; then
+		private_remove_dependees ${SPELLS[i]}
+		hash_unset "libdepends" "${SPELLS[i]}"
+		SPELLS[i]=""
+	fi
   done
   
   for SPELL in ${SPELLS[*]} ; do
@@ -235,11 +232,127 @@ function compute_depends()
     eval "$outVar=\"${!outVar}${SPELL}: "`hash_get "libdepends" "$SPELL"`$'\n'\"
   done
 
-  SPELLS="$BASE_SPELLS"
-
+  SPELLS="${BASE_SPELLS[*]}"
 }
 
-function depends()
+
+function real_depends()
+{
+    local INST
+    if ! codex_does_spell_exist $1 &> /dev/null; then
+        select_provider "INST" "$4" "$@"
+        [[ $? ]]     || return 1
+        [[ ! $INST ]] && return 1
+        local PROVIDERNAME=$1
+        shift
+        work_depends "$INST" "$@"
+        work_optional_depends "no_question" "$PROVIDERNAME" "$INST" ""
+
+    else
+        work_depends      "$@"
+    fi
+}
+
+
+function real_requires() 
+{ 
+	#deprecated, martin 20030906
+    depends "$@"
+}
+
+
+function real_optional_depends()
+{
+    local INST
+
+    if ! codex_does_spell_exist $1 &> /dev/null; then
+
+        select_provider "INST" "$4" "[none]" "$@"
+        [[ $? ]] || return 1
+        [[ ! $INST ]] && return 0
+        [[ $INST == "[none]" ]] &&
+          work_optional_depends "no_question" "$1" "$INST" "$3" && return 0
+        local PROVIDERNAME=$1
+        shift
+        work_optional_depends "no_question" "$INST" "$@"
+        work_optional_depends "no_question" "$PROVIDERNAME" "$INST" ""
+
+    else
+        work_optional_depends "$@" 
+    fi
+}
+
+
+#---------------------------------------------------------------------
+##=item select_provider <return_var> <provider> <reasontext> <elements,..>
+## 
+## gives the user some nice select list and puts the selected
+## spell in return_var
+##
+#---------------------------------------------------------------------
+function select_provider()
+{
+    local INSTALLED=false
+    local returnvar=$1
+    local reasontext=$2
+    shift; shift
+
+    if [[ $1 == '[none]' ]]; then
+        local ASK_NONE=true
+        shift
+    fi
+
+    local TO_STORE="`grep "^$SPELL:$1:providedby:optional:.*:.*$" $DEPENDS_STATUS | cut -d':' -f 5 | tail -n 1`"
+
+    if [ -z "$TO_STORE" ]; then
+
+      if [[ "$ASK_NONE" == true ]]; then
+        message -n "$SPELL_COLOR$SPELL$DEFAULT_COLOR optionally needs some "
+        message "$SPELL_COLOR$1$DEFAULT_COLOR. ($reasontext)"
+      else
+        message -n "$SPELL_COLOR$SPELL$DEFAULT_COLOR needs some "
+        message "$SPELL_COLOR$1$DEFAULT_COLOR as a requirement."
+      fi
+
+      local INST_PROV_LIST temp spell
+      local CANDIDATES=$( find_providers $1 )
+
+      for spell in $CANDIDATES; do
+          if spell_installed $spell || spell_held $spell; then
+              [[ $INSTALLED == false ]] && INST_PROV="$spell"
+              INSTALLED=true
+          fi
+
+          if ! spell_exiled $spell; then
+              temp="$temp $spell"
+          fi
+      done
+
+      if [[ $INSTALLED == true ]]; then
+          message -n "$SPELL_COLOR$1$DEFAULT_COLOR is already provided " 
+          message   "by $SPELL_COLOR$INST_PROV$DEFAULT_COLOR"
+          if query "Do you want to use that?" "y"; then
+              eval ''$returnvar'='$INST_PROV''
+              return 0
+          fi 
+      fi
+
+      if [[ ! $temp ]]; then
+          echo "Cannot satisfy requirements for $1"
+          return 1
+      fi
+
+      if [[ $ASK_NONE == true ]]; then
+          select_list "TO_STORE" "[none]" $temp
+      else
+          select_list "TO_STORE" $temp
+      fi
+    fi
+    eval ''$returnvar'='$TO_STORE''
+}
+
+
+function work_depends()
 {
 
   if spell_exiled $1 ; then 
@@ -247,11 +360,18 @@ function depends()
     return 1
   fi
   private_common_depends "$1" "on" "required" "$2" "$3"
-
 }
-function optional_depends()
-{
 
+
+function work_optional_depends()
+{
+  local NOQUESTION=false
+
+  if [[ "$1" == "no_question" ]]; then
+		shift;
+		NOQUESTION=true
+  fi
+	
   if spell_exiled $1 ; then 
     message "${SPELL_COLOR}$1${DEFAULT_COLOR} has been exiled!"
     return 1
@@ -263,22 +383,34 @@ function optional_depends()
   #See if there are preferences already
   #example: icewm:imlib:off:optional:--with-imlib:--with-xpm
   explode "`search_depends_status "$SPELL" "$1"`" ":" "status"
-  if [[ $RECONFIGURE ]] || ! [[ ${status[2]} ]] ; then
-debug "DB" "status: ${status[*]}"
-    message "${SPELL_COLOR}$1${DEFAULT_COLOR} is an optional dependency for ${SPELL_COLOR}$SPELL${DEFAULT_COLOR} ($4)"
-    if spell_installed $1 || spell_held $1 ; then
-      query "Do you want to use ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "y" && 
-        install="on"
-    else
-      query "Do you want to cast ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "n" && 
-        install="on"
-    fi
-  elif [[ ${status[2]} == on ]] ; then
-    install="on"
-  fi
-  private_common_depends "$1" "$install" "optional" "$2" "$3"
+	
+  if [[ $RECONFIGURE ]] || ! [[ ${status[2]} && ${status[2]} != "providedby" ]] ; then
 
+		if [[ $NOQUESTION == false ]]; then
+			message "${SPELL_COLOR}$1${DEFAULT_COLOR} is an optional dependency for ${SPELL_COLOR}$SPELL${DEFAULT_COLOR} ($4)"
+
+			if spell_installed $1 || spell_held $1 ; then
+				query "Do you want to use ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "y" && 
+					install="on"
+			else
+				query "Do you want to cast ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "n" && 
+					install="on"
+      fi
+		else
+			if codex_does_spell_exist $1 >/dev/null; then
+				install="on"
+			else # in this case, it's a provider and they said [none]
+				install="providedby"
+			fi
+  	fi
+
+  elif [[ ${status[2]} == on ]] ; then
+		install="on"
+  fi
+
+  private_common_depends "$1" "$install" "optional" "$2" "$3"
 }
+
 
 #---------------------------------------------------------------------
 ##=item requires <"provides" specification>
@@ -288,64 +420,61 @@ debug "DB" "status: ${status[*]}"
 ## C<requires email-client> returns true if evolution is installed.
 ##
 #---------------------------------------------------------------------
-requires()  { 
-
-  local CANDIDATES SATISFIED CANDIDATE 
-  local temp found
-
-  CANDIDATES=$(  find_providers  $1  )
-
-  for   CANDIDATE  in       $CANDIDATES;  do
-	if spell_installed $CANDIDATE	|| spell_held $CANDIDATE ; then
-	   message "${SPELL_COLOR}${SPELL}${QUERY_COLOR} requires a" \
-  	   	"${MESSAGE_COLOR}$1${DEFAULT_COLOR}."
-	   message "You already have ${SPELL_COLOR}${CANDIDATE}${DEFAULT_COLOR} providing that. "\
-	    "Using ${SPELL_COLOR}${CANDIDATE}${DEFAULT_COLOR}."
-	   CANDIDATES="$CANDIDATE"
-	   SATISFIED="true"
-	   break
-	 else
-        temp="$temp"$'\n'"$CANDIDATE"
-	fi	 
-  done
-  if ! [[ $SATISFIED ]] ; then
-    message  "${SPELL_COLOR}${SPELL}${QUERY_COLOR} requires a"  \
-             "${MESSAGE_COLOR}$1${DEFAULT_COLOR}"   \
-             "which can be provided by:"
-    message  "${FILE_COLOR}$CANDIDATES${DEFAULT_COLOR}"
-
-    SATISFIED="false"
-    for  CANDIDATE  in  $CANDIDATES;  do
-      if    query "Cast ${SPELL_COLOR}$CANDIDATE${DEFAULT_COLOR}? " "y"  && 
-            depends  $CANDIDATE
-      then  SATISFIED="true";  break
-      else
-            message "Didn't cast ${SPELL_COLOR}$CANDIDATE${DEFAULT_COLOR}."
-      fi
-    done
-  fi
-  
-  if [[ $SATISFIED ]] ; then
-    private_common_depends "$CANDIDATE" "on" "required" "" ""
-  else
-    return 1
-  fi
-  
-}
+#requires()  { #deprecated, martin 20030906 
+#
+#  local CANDIDATES SATISFIED CANDIDATE 
+#  local temp found
+#
+#  CANDIDATES=$(  find_providers  $1  )
+#
+#  for   CANDIDATE  in       $CANDIDATES;  do
+#	if spell_installed $CANDIDATE	|| spell_held $CANDIDATE ; then
+#	   message "${SPELL_COLOR}${SPELL}${QUERY_COLOR} requires a" \
+#  	   	"${MESSAGE_COLOR}$1${DEFAULT_COLOR}."
+#	   message "You already have ${SPELL_COLOR}${CANDIDATE}${DEFAULT_COLOR} providing that. "\
+#	    "Using ${SPELL_COLOR}${CANDIDATE}${DEFAULT_COLOR}."
+#	   CANDIDATES="$CANDIDATE"
+#	   SATISFIED="true"
+#	   break
+#	 else
+#        temp="$temp"$'\n'"$CANDIDATE"
+#	fi	 
+#  done
+#  if ! [[ $SATISFIED ]] ; then
+#    message  "${SPELL_COLOR}${SPELL}${QUERY_COLOR} requires a"  \
+#             "${MESSAGE_COLOR}$1${DEFAULT_COLOR}"   \
+#             "which can be provided by:"
+#    message  "${FILE_COLOR}$CANDIDATES${DEFAULT_COLOR}"
+#
+#    SATISFIED="false"
+#    for  CANDIDATE  in  $CANDIDATES;  do
+#      if    query "Cast ${SPELL_COLOR}$CANDIDATE${DEFAULT_COLOR}? " "y"  && 
+#            depends  $CANDIDATE
+#      then  SATISFIED="true";  break
+#      else
+#            message "Didn't cast ${SPELL_COLOR}$CANDIDATE${DEFAULT_COLOR}."
+#      fi
+#    done
+#  fi
+#  
+#  if [[ $SATISFIED ]] ; then
+#    private_common_depends "$CANDIDATE" "on" "required" "" ""
+#  else
+#    return 1
+#  fi
+#  
+#}
 
 
 function private_common_depends()
 {
-debug "DB" "private_common_depends - $*"
   add_depends "$SPELL" "$@"
   
   if [[ $2 == on ]] && private_should_cast $1 ; then
-debug "DB" "adding a new depends here."
     NEW_DEPENDS=( "${NEW_DEPENDS[@]}" $1 )
   fi
   
   return 0
-
 }
 
 
@@ -361,22 +490,22 @@ function private_remove_installed_spells()
   done
   
   SPELLS=( ${SPELLS[*]} ) #Compact the array
-  
 }
+
 
 function private_run_depends()
 {
 
   SPELL="$*"
   NEW_DEPENDS=()
-#  private_mark_spell  &&
+  
   run_prepare     	  && 
   run_details     	  && 
   run_configure   	  && 
   run_depends $1  	  && 
-  private_add_depends
-  
+  private_add_depends 
 }
+
 
 function private_add_depends()
 {
@@ -391,9 +520,6 @@ function private_add_depends()
     done
   done
   SPELLS=( "${SPELLS[@]}" ${NEW_DEPENDS[*]} )
-
-  debug "DB" "adding ${NEW_DEPENDS[*]}"
-
 }
 
 
@@ -402,13 +528,33 @@ function private_list_dependees()
 
   local i
   for (( i=0 ; "${SPELLS[$i]}"!="$SPELL" ; i++ )) ; do
-    is_member "$1" `hash_get "libdepends" "${SPELLS[$i]}"` && echo $1
+    is_member "$1" `hash_get "libdepends" "${SPELLS[$i]}"` && echo $i
   done
+}
 
+function private_remove_dependees()
+{
+
+	local spell i
+	echo "Removing dependees of $1"
+
+	# spell is being removed from cast list, add to FAILED_LIST
+	echo "$1" >> $FAILED_LIST
+
+	for spell in $(private_list_dependees $1) ; do
+		hash_unset "libdepends" "${SPELLS[spell]}"
+		SPELLS[spell]=""
+		for ((i=0;i<${#BASE_SPELLS[*]}; i++)) ; do
+			[[ $spell == ${BASE_SPELLS[i]} ]] && BASE_SPELLS[i]=""
+		done
+	done
+	SPELLS=( ${SPELLS[*]} )
+	BASE_SPELLS=( ${BASE_SPELLS[*]} )
 }
 
 function private_should_cast()
 {
+	codex_does_spell_exist $1						&&
   ( echo "$PRETEND_NOT_INSTALLED" | grep -q $1 		||
 	! ( spell_installed $1	|| 	spell_held $1 ))	&&
 	! spell_exiled $1 		;
