make scribe add/update through rsync verify the tree using a manifest file (bug 8220). This is the last gpg related issue bug 7837 can be closed at last. Document scribe add from rsync (bug 8609) Fix issues brought up in bug 9701

diff --git a/usr/sbin/scribe b/usr/sbin/scribe
--- a/usr/sbin/scribe
+++ b/usr/sbin/scribe
@@ -44,10 +44,83 @@ localize	grimoire	Makes a grimoire local
 				 (so scribe won't try to update it)
 unlocalize	grimoire	Makes a grimoire nonlocal
 
+
+Grimoire tarballs are located at $CODEX_TARBALL_URL
+Grimoire rsync modules are located at $CODEX_RSYNC_URL
+
 EOF
 
   exit  1
 }
+
+
+#---------------------------------------------------------------------
+## Common error messag when downloading a grimoire fails.
+#---------------------------------------------------------------------
+function scribe_download_fail_error_msg() {
+    message "Error downloading grimoire..."
+    message "Grimoire tarballs are located at $CODEX_TARBALL_URL"
+    message "Grimoire rsync modules are located at $CODEX_RSYNC_URL"
+}
+
+#---------------------------------------------------------------------
+## Unpackage a grimoire tarball and make sure it worked
+#---------------------------------------------------------------------
+function unpackage_grimoire_tarball() {
+  local tarball=$1
+  local grimoire=$2
+  local grim_name=$3
+  #untar the new grimoire update and remove zip
+  bzcat $tarball| tar -x  1>/dev/null 2>&1
+  #check for a successful unzip
+  if ! [ -d $grimoire ]; then
+    #uh oh! bad unzip.
+    message "ERROR: Grimoire tarball for $grim_name not" \
+            "formated correctly!."
+    return 1
+  fi 
+  return 0
+}
+
+#---------------------------------------------------------------------
+## Given an rsync url, make sure it has a / on the end of it
+## so downloading works.
+#---------------------------------------------------------------------
+function sanitize_rsync_url() {
+  # add a / to the end, if one isnt there, if the user types
+  # rsync://sourcemage.org::codex/games instead of
+  # rsync://sourcemage.org::codex/games/ strange things happen
+  if list_find "rsync" $prefix ; then
+    echo $from|sed 's!\([^/]\)$!\1/!'
+  else
+    echo $from
+  fi
+}
+
+#---------------------------------------------------------------------
+## Validate a grimoire tree using a manifest
+#---------------------------------------------------------------------
+function scribe_validate_tree_common() {
+  local scribe_target=$1
+  local grim_name=$2
+  local grimoire=$3
+    if ! test -d "$scribe_target"; then
+      message "Downloaded a tree but directory doesn't exist! file a bug if you see this"
+      return 1
+    fi
+    if [[ "$scribe_target" != "$grim_name" ]] ; then
+      mv -f "$scribe_target" "$grim_name"
+    fi
+
+    verify_grimoire_tree "$grim_name" "$grimoire"
+    local rc=$?
+    if [[ $rc != 0 ]] && [[ $rc != 253 ]] ; then
+      pushd $grim_dir >/dev/null
+      grimoire_tree_user_query "$grim_name" || return 1
+      popd >/dev/null
+    fi
+}
+
 
 #---------------------------------------------------------------------
 ## scribe_add
@@ -81,9 +154,11 @@ function scribe_add() {
               "the name $grimoire! Refusing to add.${DEFAULT_COLOR}"
       continue
     fi
+
     # derive a full grimoire name
     grimoire=$(codex_canonicalize_grimoire_name $grimoire)
-    scribe_add_worker $grimoire $from
+    message "Adding grimoire $grim_name to $grim_dir from $from"
+    scribe_add_update_worker "$grimoire" "$from" add
   done
 }
   
@@ -97,133 +172,124 @@ function scribe_add() {
 ## @param location to download from (optional), if empty use $CODEX_URL
 ##
 #---------------------------------------------------------------------
-function scribe_add_worker() {
+function scribe_add_update_worker() {
   $STD_DEBUG
   local grimoire=$1
   local from=$2
+  local add_or_update=$3
 
   if [ -z $grimoire ] ; then
-    message "Empty grimoire name! Please contact the sorcery team"
+    message "Empty grimoire name! Please contact the sorcery team if" \
+            "you see this"
     return 1
+  fi
+
+  if [[ $add_or_update == update ]] ; then
+    if ! test -d $grimoire ; then
+      message "$grimoire is not a directory! refusing to update"
+      return 1
+    fi
   fi
 
   local grim_dir=$(dirname $grimoire)
   local grim_name=$(basename $grimoire)
-  local grim_target="$grim_name.tar.bz2"
+  pushd $grim_dir &> /dev/null
 
-  local prefix
-  #If the associated FROM is not empty, check it for validity
+  # get the url, if one was specified sanity check it
   if  [ -n "$from" ];  then
-    if url_is_valid "$from"; then
-      prefix=$(url_get_prefix $from)
-      if list_find "rsync svn cvs smgl_tla dir" $prefix ; then
-        grim_target=$grim_name
-      fi
-    else
+    if ! url_is_valid "$from"; then
       #if not valid, use default
       message  "Error: $from is not a recognized url. Using default."
       from=""
+    else
+      grim_target=$(basename $from)
     fi
   fi
 
+  local prefix
   if  [ -z "$from" ];  then
     #from is empty - use the default
     prefix=$(url_get_prefix $CODEX_URL)
-    # yet another hard-coded list
     if list_find "rsync svn cvs smgl_tla dir" $prefix ; then
       grim_target=$grim_name
+    else
+      grim_target="$grim_name.tar.bz2"
     fi
     from="$CODEX_URL/$grim_target"
   fi
 
-  # add a / to the end, if one isnt there, if the user types
-  # rsync://sourcemage.org::codex/games instead of
-  # rsync://sourcemage.org::codex/games/ strange things happen
-  if list_find "rsync" $prefix ; then
-    from=$(echo $from|sed 's!\([^/]\)$!\1/!')
+  local prefix=$(url_get_prefix $from)
+  from=$(sanitize_rsync_url $prefix $from)
+
+
+  # do some cleanup before downloading
+  if [[ $add_or_update == add ]] ; then
+    if test -d $grimoire ; then
+      message "Found an old grimoire directory, removing it..."
+      rm -rf $grimoire
+    fi
   fi
+  test -f $grim_target && rm -f $grim_target
 
-  message "Adding grimoire $grim_name to $grim_dir from $from"
-
-  #switch to and work in the codex
-  pushd $grim_dir &> /dev/null
-
-  if test -d $grimoire ; then
-    message "Found an old grimoire directory, removing it..."
-    rm -rf $grimoire
-  fi
-  if test -f $grim_target; then
-    rm -f $grim_target
-  fi
-
+  # download it
   local scribe_target scribe_type
-  url_download $grim_target $from "" scribe_target scribe_type
+  url_download "$grim_target" "$from" "" scribe_target scribe_type
 
   #check the success of the download
   if [ $? != 0 ]; then
-    message "Error downloading grimoire..."
+    scribe_download_fail_error_msg
     popd &>/dev/null
     return 1
   fi
 
+  # do result specific actions
+  local rc
   if [[ "$scribe_type" == file ]] ; then
-    local tarball=$scribe_target
 
-    gpg_verify_grimoire $PWD/$tarball $(dirname $from)
+    gpg_verify_grimoire $PWD/$scribe_target $(dirname $from)
     rc=$?
+    gpg_user_query $rc $(basename $from) grimoire || return 1
 
-    gpg_user_query $rc || return 1
-    #if successfuly downloaded, untar it and remove the zip
-    bzcat $tarball | tar -x  1>/dev/null 2>&1
-    rm $tarball
-    #make sure that it untarred to the proper dir.
-    if [ -d $grimoire ]; then
-      :
-    elif  [ -d $grim_dir/grimoire ]; then
-      mv -f $grim_dir/grimoire $grimoire
-    else
-      local tmp_name=$grim_dir/${tarball/tar.bz2/}
-      if  [ -d $tmp_name ]; then
-        mv -f $tmp_name $grimoire
-      else
-        message "ERROR: Grimoire tarball for $grimoire not formated correctly!"
-        return 1
+    [[ $add_or_update == update ]] && mv $grim_name temp_$grim_name.old
+
+    if unpackage_grimoire_tarball "$scribe_target" "$grimoire" "$grim_name"
+    then
+      rm $scribe_target
+      if [[ $add_or_update == update ]] && [ -d temp_$grim_name.old ]; then
+        rm -rf temp_$grim_name.old
       fi
+    else
+      # restore from backup
+      [[ $add_or_update == update ]] && mv -f temp_$grim_name.old $grim_name
+      popd &>/dev/null; return 1
     fi
   elif [[ "$scribe_type" == tree ]]; then
-    if ! test -d "$scribe_target"; then
-      message "Downloaded a tree but directory doesn't exist! file a bug if you see this"
-      return 1
+    if ! scribe_validate_tree_common "$scribe_target" "$grim_name" "$grimoire"
+    then
+      popd &>/dev/null; return 1
     fi
-    if [[ "$scribe_target" != "$grim_name" ]] ; then
-      mv -f "$scribe_target" "$grim_name"
-    fi
-
-    #FIXME gpg verification
-    # see bug 8220
   else
     message "Unknown download type $scribe_type, file a bug if you see this"
     return 1
   fi
   popd &>/dev/null
 
-
   #success! create a GRIMOIRE file that stores where it was downloaded from
   echo "FROM_URL=$from" > $grimoire/GRIMOIRE && 
   chmod +x $grimoire/GRIMOIRE && 
-  codex_add_grimoire $grimoire 0 && 
-  codex_create_cache $grimoire && 
-  message "Grimoire \"$grimoire\" successfully added to your codex." ||
-  {
-    #dir not found. error.
-    #FIXME- add a check for what dir it was and remove that
-    message "ERROR: Grimoire tarball for $grimoire not formated correctly!"
-    return 1
-  }
+
+  if [[ $add_or_update == add ]] ; then
+    codex_add_grimoire $grimoire 0 &&
+    scribe_reindex $grimoire
+    message "Grimoire \"$grimoire\" successfully added to your codex."
+  else
+    scribe_reindex $grimoire
+    message "$grim_name Updated!"
+    grimoire_history $grimoire
+  fi
 
   return 0
 }
-
 #---------------------------------------------------------------------
 ## scribe_fix
 ##
@@ -512,7 +578,8 @@ function scribe_update() {
       fi
 
       if codex_is_local $grimoire; then
-        message "${SPELL_COLOR}$grim${MESSAGE_COLOR} is being marked as local. Won't update.${DEFAULT_COLOR}"
+        message "${SPELL_COLOR}$grim${MESSAGE_COLOR} is being marked" \
+                "as local. Won't update.${DEFAULT_COLOR}"
         if [[ "$2" == "from" ]] ; then shift 3 ; else  shift 1 ; fi
         continue
       fi
@@ -521,11 +588,6 @@ function scribe_update() {
       # get a url if one exists
       if [ "$2" == "from" ] ; then
         from=$3
-        if [ -z $from ] || ! url_is_valid "$from"; then
-          local bad_from=$from
-          from=$FROM_URL
-          message "Error: \"$bad_from\" is not a valid URL. Using: $from"
-        fi
         shift 3
       else
         from=$FROM_URL
@@ -533,8 +595,7 @@ function scribe_update() {
       fi
 
       message "Updating grimoire $grim from $from"
-      scribe_do_update $grimoire $from &&
-      scribe_reindex $grimoire ||
+      scribe_add_update_worker "$grimoire" "$from" update ||
       let rc++
     done
   else
@@ -554,108 +615,13 @@ function scribe_update() {
 
       #include metadata
       . $grimoire/GRIMOIRE
-      from=$FROM_URL
       message "Updating grimoire $grim from $from"
-      scribe_do_update $grimoire $from &&
-      scribe_reindex $grimoire ||
+      scribe_add_update_worker "$grimoire" "$FROM_URL" update ||
       let rc++
     done
   fi
   tablet_import_repair_files $TABLET_PATH
   return $rc
-}
-
-#---------------------------------------------------------------------
-## scribe_do_update
-##
-## actually update a grimoire
-##
-## @param full path to a grimoire
-## @param url to get the grimoire from
-##
-#---------------------------------------------------------------------
-function scribe_do_update() {
-  #switch to codex for update
-  local grimoire=$1
-  local from=$2
-  if ! codex_is_canonicalized $grimoire ; then
-    message "$grimoire is not canonicalized, this may be a sorcery bug," \
-            "please let us know if you see this. Bailing out."
-    exit 1
-  fi
-
-  if ! test -d $grimoire ; then
-    message "$grimoire is not a directory! refusing to update"
-    return 1
-  fi
-
-  local grim_dir=$(dirname $grimoire)
-  local grim_name=$(basename $grimoire)
-  local grim_target=$(basename $from)
-  pushd $grim_dir &> /dev/null
-
-  local scribe_target scribe_type
-  url_download "$grim_target" "$from" "" scribe_target scribe_type
-
-  #check the success of the download
-  if [ $? != 0 ] ; then
-    #grimoire was not downloaded. Error message.
-    message "Error downloading grimoire..."
-    return 1
-  fi
-
-  local rc
-  if [[ "$scribe_type" == file ]] ; then
-
-    gpg_verify_grimoire $PWD/$(basename $from) $(dirname $from)
-    rc=$?
-
-    gpg_user_query $rc $(basename $from) grimoire || return 1
-
-    #if the grimoire is an archive, untar it
-    #backup old version until successful untar
-    mv $grim_name temp_$grim_name.old
-
-    #untar the new grimoire update and remove zip
-    bzcat $scribe_target | tar -x  1>/dev/null 2>&1
-    rm $scribe_target
-
-    #check for a successful unzip
-    if [ -d $grimoire ]; then
-
-      #and remove backup version
-      if [ -d temp_$grim_name.old ]; then
-        rm -rf temp_$grim_name.old
-      fi
-
-      #Confirm Success!
-      message "$grim_name Updated!"
-      grimoire_history $grimoire
-    else
-      #uh oh! bad unzip.
-      message "ERROR: Grimoire tarball for $grim_name not formated correctly! Reverting."
-      #phew! we backed it up. restore backed up version
-      mv -f temp_$grim_name.old $grim_name
-    fi 
-  elif [[ "$scribe_type" == tree ]]; then
-    if ! test -d "$scribe_target"; then
-      message "Downloaded a tree but directory doesn't exist! file a bug if you see this"
-      return 1
-    fi
-    if [[ "$scribe_target" != "$grim_name" ]] ; then
-      mv -f "$scribe_target" "$grim_name"
-    fi
-    # FIXME gpg verify tree
-  else
-    message "Unknown download type $scribe_type, file a bug if you see this"
-    return 1
-  fi
-  #success! create metadata
-  echo "FROM_URL=$from" > $grimoire/GRIMOIRE
-  chmod +x $grimoire/GRIMOIRE
-
-  #return to directory scribe was run from
-  popd &>/dev/null
 }
 
 #---------------------------------------------------------------------
diff --git a/var/lib/sorcery/modules/libgpg b/var/lib/sorcery/modules/libgpg
--- a/var/lib/sorcery/modules/libgpg
+++ b/var/lib/sorcery/modules/libgpg
@@ -136,6 +136,46 @@ function gpg_verify_grimoire() {
   gpg_verify_common $FILENAME $SOURCE_URL $gpg_pub_key grimoire $SIGNATURE
 }
 
+
+
+function verify_grimoire_tree() {
+  local grimoire_name=$1
+  local grimoire_dir=$2
+
+  if [[ "$GPG_VERIFY_GRIMOIRE" != on ]] ; then
+    return 253
+  fi
+
+  local gpg_pub_key=$(gpg_get_grimoire_key $grimoire_name)
+  if test -z $gpg_pub_key && test -f $gpg_pub_key ; then
+    message "No keyring found! (maybe you need to cast sorcery-pubkeys?)"
+    return 254
+  fi
+
+  manifest=$grimoire_name.manifest.$GRIMOIRE_MANIFEST_ALGORITHM
+  manifest_url=${CODEX_MANIFEST_URL}/$manifest
+
+  pushd $TMP_DIR >/dev/null || return 1
+
+  local manifest_target manifest_type
+  url_download $manifest $manifest_url "" manifest_target manifest_type
+  #check the success of the download
+  if [ $? != 0 ] || [[ "$manifest_type" != file ]] ; then
+    message "Error downloading manifest..."
+    return 1
+  fi
+
+  gpg_verify_common $manifest $CODEX_MANIFEST_URL $gpg_pub_key "grimoire manifest"
+  if ! gpg_user_query $?; then
+    return 2
+  fi
+
+  popd >/dev/null
+
+  verify_grimoire_against_manifest "$grimoire_dir" "$TMP_DIR/$manifest" \
+                                   "$GRIMOIRE_MANIFEST_ALGORITHM"
+}
+
 #---------------------------------------------------------------------
 ## Verify a sorcery tarball's gpg signature
 ## @param file on local disk to verify
@@ -293,6 +333,96 @@ function gpg_get_hashes() {
   gpg --version 2> /dev/null | grep '^Hash' | awk -F: '{ print $2 }' | tr , ' ' | tr 'A-Z' 'a-z'
 }
 
+#---------------------------------------------------------------------
+## Verify a tree against a manifest file
+## @param directory to verify
+## @param manifest file, the format is like what the md5sum tool would
+##        produce
+## @param algorithm to use, this can be anything supported by gpg
+## @param regular expression of files to ignore
+#---------------------------------------------------------------------
+function verify_against_manifest() {
+  local dir=$1
+  local manifest=$2
+  local algorithm=$3
+  local ignore=$4
+  local base=$(basename $dir)
+  local real_list=$TMP_DIR/$base
+  local missing=$TMP_DIR/missing.$base
+  local rc=0
+
+  message "Validating tree at $dir with $manifest"
+  local manifest_format=$(echo $manifest|awk -F. '{print $NF}')
+
+  pushd $dir > /dev/null || return $?
+  find . -type f > $real_list
+  { cat $real_list $real_list ; awk '{print $NF}' $manifest ; } |
+  sort | uniq -c | grep -v '^ *3' | grep -v "$ignore" > $missing
+  NO_TREE=$(grep "^ *1" $missing|sed 's/^ *1 //')
+  if [[ $NO_TREE ]] ; then
+    message "${PROBLEM_COLOR}The following exist only in the manifest" \
+            "and are missing from the tree!${DEFAULT_COLOR}"
+    echo "$NO_TREE"|$PAGER
+    let rc+=1
+  fi
+  NO_MANIFEST=$(grep "^ *2" $missing|sed 's/^ *2 //')
+  if [[ $NO_MANIFEST ]] ; then
+    message "${PROBLEM_COLOR}The following exist only in the tree" \
+            "and are missing from the manifest!${DEFAULT_COLOR}"
+    echo "$NO_MANIFEST"|$PAGER
+    let rc+=1
+  fi
+  local hash r
+  while read hashsum file; do
+    local hash=$(gpg_hashsum $algorithm $file 2>/dev/null|cut -f1 -d' ')
+    r=$?
+    if [[ $hash != $hashsum ]] || [[ $r != 0 ]]; then
+      NOT_OK=( $NOT_OK "$file" )
+    fi
+  done < $manifest
+
+  if [[ $NOT_OK ]] ; then
+    message "${PROBLEM_COLOR}The following have bad checksums${DEFAULT_COLOR}"
+    echo "$NOT_OK"
+    let rc+=1
+  fi
+  popd $dir > /dev/null
+  return $rc
+}
+
+#---------------------------------------------------------------------
+## Verify a grimoire tree and ignore files sorcery adds post-download
+#---------------------------------------------------------------------
+function verify_grimoire_against_manifest() {
+  verify_against_manifest $1 $2 $3 \
+                          '^ *2 \./\(GRIMOIRE\|codex\.index\|provides\.index\)$'
+}
+
+#---------------------------------------------------------------------
+## Ask the user what they want to do if verification of a grimoire tree
+## fails.
+#---------------------------------------------------------------------
+function grimoire_tree_user_query() {
+  local grimoire_name=$1
+  message "${PROBLEM_COLOR}Verification of the grimoire" \
+          "tree ${DEFAULT_COLOR}${SPELL_COLOR}$grimoire_name" \
+          "${DEFAULT_COLOR}${PROBLEM_COLOR}failed!"
+  message "What would you like to do?${DEFAULT_COLOR}"
+  local choice
+  select_list choice 0 "set aside" "remove" "ignore"
+  case "$choice" in
+    "set aside") local tgt=$grimoire_name.$(date +%Y%m%d%H%M).corrupt
+                 message "moving grimoire to $tgt"
+                 mv $grimoire_name $tgt
+                 scribe_remove $grimoire_name &>/dev/null
+                 ;;
+         remove) rm -rf $grimoire_name
+                 scribe_remove $grimoire_name &>/dev/null;;
+         ignore) return 0 ;;
+  esac
+  return 1
+}
+ 
 #---------------------------------------------------------------------
 ## This software is free software; you can redistribute it and/or modify
 ## it under the terms of the GNU General Public License as published by
