fix some issues with compile log generation when cast is aborted due to md5 unpacking problems.

diff --git a/var/lib/sorcery/modules/build_api/api1 b/var/lib/sorcery/modules/build_api/api1
--- a/var/lib/sorcery/modules/build_api/api1
+++ b/var/lib/sorcery/modules/build_api/api1
@@ -24,12 +24,22 @@
 #---------------------------------------------------------------------
 function run_build_spell() {
   debug "build_api/api1" "run_build_spell"
-  run_pre_build                         &&
-  run_build                             &&
+  C_LOG=/tmp/$SPELL.compile.log
+  C_FIFO=/tmp/$SPELL.compile.fifo
+  rm -f $C_LOG
+  rm -f $C_FIFO
+  touch $C_LOG
+  mkfifo $C_FIFO
+
+  # This is an experiment, If we have actual interesting return codes
+  # from here, the caller can figure out what to do
+  # as opposed to trying to cram it all in here
+  run_pre_build                         || return 1
+  run_build                             || return 2
   run_post_build                        &&
-  run_post_install                      &&
-  run_triggers                          &&
-  return 0 || return 1
+  run_post_install                      || return 3
+  run_triggers                          || return 4
+  return 0
 }
 #---------------------------------------------------------------------
 ## This phase of casting involves unpacking the source into the
@@ -65,12 +75,6 @@ function run_pre_build() {
 function run_build()  {
 
   debug "build_api/api1" "Starting run_build()"
-   C_LOG=/tmp/$SPELL.compile.log
-  C_FIFO=/tmp/$SPELL.compile.fifo
-
-  rm  -f $C_FIFO
-  mkfifo  $C_FIFO
-  rm  -f $C_LOG
 
   echo  "Compile log for $SPELL  $VERSION  Built on `date  -u`"  >  $C_LOG
   echo  "Using gcc version: `gcc -dumpversion`" >> $C_LOG
