lots of stuff, this fixes bugs 7545, 7536, 6281 and 1879, it also partially addresses bugs 7477 and 7550 main new stuff is the delve tool to run parts of a spell, and the installed grimoire (aka the tablet) lots of other code churning mostly related to converting to using $TMP_DIR instead of /tmp, and some other changes that utilize the tablet or were needed to make it work, some latent bugs in install_root/track_root were addressed by having a tool to adjust log files to different formats depending on the situation

diff --git a/var/lib/sorcery/modules/build_api/common b/var/lib/sorcery/modules/build_api/common
--- a/var/lib/sorcery/modules/build_api/common
+++ b/var/lib/sorcery/modules/build_api/common
@@ -110,7 +110,7 @@ function run_config_loc () {
       fi
 
       if    query  "Do you wish to add -- options to ./configure?"  n ;  then
-				F_TMP=/tmp/cast.$$.configure
+	F_TMP=$TMP_DIR/cast.$$.configure
         rm -f $F_TMP
 				
         if [ -x ./configure ]; then
@@ -256,18 +256,18 @@ function run_spell_success() {
     local MD5_LOG="$MD5SUM_LOGS/$SPELL-$VERSION"
     local TMP_INST_LOG="$TMP_DIR/$SPELL-$VERSION.install"
     local TMP_MD5_LOG="$TMP_DIR/$SPELL-$VERSION.md5"
-    local CACHE_COMP="$INSTALL_CACHE/$SPELL-$VERSION-$BUILD.tar$EXTENSION"
+    local CACHE="$INSTALL_CACHE/$SPELL-$VERSION-$BUILD.tar"
+    local CACHE_COMP=${CACHE}${EXTENSION}
     local C_LOG_COMP="$COMPILE_LOGS/$SPELL-$VERSION$EXTENSION"
 
     sound  SUCCESS
 
-    create_compile_log
-    view_compile_log
-
+    # announce to everyone the spell succeeded
     activity_log  "cast"  "$SPELL"  "$VERSION"  "success"
     add_spell $SPELL installed $VERSION
     echo $SPELL >> $SUCCESS_LIST
 
+    # update depends info
     debug "build_api/common" "Merging depends info"
     local t_DEPENDS_STATUS=$(lock_start_transaction $DEPENDS_STATUS)
     # none of the old values are valid, only the new, uncommitted values are
@@ -275,36 +275,57 @@ function run_spell_success() {
     local spell_depends=$(hash_get uncommitted_hash $SPELL)
     if [ -e $spell_depends ] ; then
       cat  $spell_depends >> $t_DEPENDS_STATUS
-      rm -f $spell_depends &>/dev/null 
     fi
     lock_commit_transaction $DEPENDS_STATUS
 
     # since the database is now accurate, no reason to keep old answers
     # floating around
-    [ -e "$ABANDONED_DEPENDS/$SPELL" ] &&
+    test -e "$ABANDONED_DEPENDS/$SPELL" &&
     rm -f $ABANDONED_DEPENDS/$SPELL &>/dev/null
 
-    # this will make the raw log that needs post processing to strip
-    # INSTALL_ROOT and insert TRACK_ROOT in its place
-    
+    # compile log
+    create_compile_log
+    view_compile_log
+
+    local tablet_dir=$(tablet_get_path $SPELL)
+    if [ "$?" != 0 ] ; then
+      message "failed to make a tablet directory: $tablet_dir" \
+              "this may be a bug"
+      unset tablet_dir
+    else
+      message  "${MESSAGE_COLOR}Creating tablet in directory"        \
+               "${FILE_COLOR}${tablet_dir}${DEFAULT_COLOR}"
+      tablet_install_spell_files $tablet_dir
+    fi
+
+    # install log
     message  "${MESSAGE_COLOR}Creating install log" \
              "${FILE_COLOR}${INST_LOG}${DEFAULT_COLOR}"
-    track $TMP_INST_LOG
-    install_log_filter $INSTALL_ROOT $TRACK_ROOT < $TMP_INST_LOG > $INST_LOG
+    # this will make a "root" format install log it will need to be
+    # reformatted to "log" format (see log_adjuster in libtrack for details)
+    # but basically replacing INSTALL_ROOT with TRACK_ROOT
+    create_install_log $IW_LOG $TMP_INST_LOG
+    if [[ $tablet_dir ]] ; then
+      find $tablet_dir >> $TMP_INST_LOG
+    fi
+    log_adjuster $TMP_INST_LOG $INST_LOG root log
 
+    # md5sum log
     message  "${MESSAGE_COLOR}Creating MD5 log"        \
              "${FILE_COLOR}${MD5_LOG}${DEFAULT_COLOR}"
-    md5list $TMP_INST_LOG $TMP_MD5_LOG
-    md5_log_filter $INSTALL_ROOT $TRACK_ROOT < $TMP_MD5_LOG > $MD5_LOG
+    create_md5list $TMP_INST_LOG $TMP_MD5_LOG
+    log_adjuster $TMP_MD5_LOG $MD5_LOG root log md5_log_filter
 
-    # archives are relative to / in their own environment, and thus
-    # INSTALL_ROOT is stripped
-    sed "s:^$INSTALL_ROOT/::" $TMP_INST_LOG | archive $INSTALL_ROOT 
+    # cache archive
+
+    # Archives are stored with INSTALL_ROOT and STATE_ROOT stripped.
+    # this way they can be unpacked anywhere and sorcery will know
+    # where things will be.
+    create_cache_archive $TMP_INST_LOG $CACHE $CACHE_COMP
 
     report_install
-
     rm_source_dir
-    rm  -f  $IW_LOG  $TMP_LOG  $CASTING $C_LOG
+    rm  -f $IW_LOG $C_LOG $TMP_INST_LOG $TMP_MD5_LOG $spell_depends
 }
 
 #---------------------------------------------------------------------
@@ -317,22 +338,27 @@ function run_spell_failure() {
 
     sound  FAILURE
 
-    if [ $rc != 1 ] ; then
-      create_compile_log
-      view_compile_log
-    fi
     activity_log "cast" "$SPELL"  "$VERSION" "failure"
     echo $SPELL >> $FAILED_LIST
 
+    # if it failed after PRE_BUILD make a compile log
+    if [ "$rc" != 1 ] ; then
+      create_compile_log
+      view_compile_log
+    fi
+
+    # put the answers somewhere where they can still be used later
+    mkdir -p $ABANDONED_DEPENDS
     local spell_depends=$(hash_get uncommitted_hash $SPELL)
-    [ -e $spell_depends ] && rm $spell_depends
+    [ -e $spell_depends ] && mv $spell_depends $ABANDONED_DEPENDS/$SPELL
 
     # This may have been locked if there was a failure during the install
     unlock_resources "libgrimoire" "install"
 
     IW_LOG="$INSTALLWATCHFILE"
-    INSTALLWATCHFILE=""
-    rm  -f  $IW_LOG  $TMP_LOG  $CASTING $C_LOG
+    devoke_installwatch
+
+    rm -f $IW_LOG $C_LOG
 
     [[  $CLEAN_SOURCE == on ]] && rm_source_dir
     CAST_EXIT_STATUS=1
