Seems to fix the optional_depends problems, bug #6365. Thanks to rycee for the fix!

diff --git a/var/lib/sorcery/modules/libdepends b/var/lib/sorcery/modules/libdepends
--- a/var/lib/sorcery/modules/libdepends
+++ b/var/lib/sorcery/modules/libdepends
@@ -152,20 +152,25 @@ function satisfy_depends()
 
     debug "libdepends" "satisfy_depends() - $LINE"
 
-    # line format is: spell:dependency:status:something:on-opts:off=opts
+    # line format is:
+    #  spell:dependency(provider):status:something:on-opts:off=opts
     DEP=()
     explode "$LINE" ":" "DEP"
+    DEP[1]=${DEP[1]%(*}   # Strip possible provider name
+
+    # If dependency name is "" then don't bother with the rest of this loop.
+    if [[ ! ${DEP[1]} ]] ; then
+      continue
+    fi
 
     # First, see if the spell exists.
     DEP_SPELL_LOCATION=`codex_find_spell_by_name ${DEP[1]}`
     if  [  -z  "$DEP_SPELL_LOCATION"  ];  then
-      if [  "${DEP[2]}"  !=  'providedby'  ]; then
-        message  "${PROBLEM_COLOR}Unable to find previously configured"  \
-                 "dependency ${SPELL_COLOR}'${DEP[1]}'${PROBLEM_COLOR}"
-        message  "in grimoire.  Removing spell from cached depends."     \
-                 "${DEFAULT_COLOR}"
-        remove_depends_status  "$SPELL"  "${DEP[1]}"
-      fi
+      message  "${PROBLEM_COLOR}Unable to find previously configured"  \
+               "dependency ${SPELL_COLOR}'${DEP[1]}'${PROBLEM_COLOR}"
+      message  "in grimoire.  Removing spell from cached depends."     \
+               "${DEFAULT_COLOR}"
+      remove_depends_status  "$SPELL"  "${DEP[1]}"
     else
 
       #Second, am I trying to cast --fix or is this just a normal cast?
@@ -248,25 +253,21 @@ function compute_depends()
   SPELLS="${BASE_SPELLS[*]}"
 }
 
-
+#---------------------------------------------------------------------
+## @param  spell or provider name
+## @param  addition to OPTS
+## @param  description
+## Delegates provider and spell cases to different worker functions.
+#---------------------------------------------------------------------
 function real_depends()
 {
-	debug "libdepends" "$FUNCNAME - $*"
-    local INST
-    if ! codex_does_spell_exist $1 &> /dev/null; then
-        select_provider "INST" "$4" "$@"
-        [[ $? ]]     || return 1
-        [[ ! $INST ]] && return 1
-		debug "libdepends" "$FUNCNAME $1 isn't a spell, provided by $INST"
-		add_depends "$SPELL" "$1" "providedby" "optional" "$INST" ""
-        local PROVIDERNAME=$1
-        shift
 
-        work_depends "$INST" "$@"
+  if ! codex_does_spell_exist $1 &> /dev/null; then
+    work_depends_provider "$@"
+  else
+    work_depends_spell "$@"
+  fi
 
-    else
-        work_depends      "$@"
-    fi
 }
 
 
@@ -276,125 +277,193 @@ function real_requires()
     depends "$@"
 }
 
-
+#---------------------------------------------------------------------
+## @param  spell or provider name
+## @param  addition to OPTS if enabled
+## @param  addition to OPTS if disabled
+## @param  description
+## Delegates provider and spell cases to different worker functions.
+#---------------------------------------------------------------------
 function real_optional_depends()
 {
-    local INST
 
-    if ! codex_does_spell_exist $1 &> /dev/null; then
+  if ! codex_does_spell_exist $1 &> /dev/null; then
+    work_optional_depends_provider "$@"
+  else
+    work_optional_depends_spell "$@" 
+  fi
 
-        select_provider "INST" "$4" "[none]" "$@"
-        [[ $? ]] || return 1
-        [[ ! $INST ]] && return 0
-
-		add_depends "$SPELL" "$1" "providedby" "optional" "$INST" ""
-        [[ $INST == "[none]" ]] && return 0
-
-        local PROVIDERNAME=$1
-        shift
-        work_optional_depends "no_question" "$INST" "$@"
-
-    else
-        work_optional_depends "$@" 
-    fi
 }
 
 
 #---------------------------------------------------------------------
-##=item select_provider <return_var> <provider> <reasontext> <elements,..>
-## 
-## gives the user some nice select list and puts the selected
-## spell in return_var
-##
+## @param  name of return variable
+## @param  provider name
+## @param  reason text
+## @param  optional switch (set to "optional" to enable)
+## Gives the user some nice select list and puts the selected spell in
+## return_var.
 #---------------------------------------------------------------------
 function select_provider()
 {
     local INSTALLED=false
     local returnvar=$1
-    local reasontext=$2
-    shift; shift
+    local provname=$2
+    local reasontext=$3
 
-    if [[ $1 == '[none]' ]]; then
-        local ASK_NONE=true
-        shift
+    if [[ $4 == "optional" ]] ; then
+      local optional=true
     fi
 
-    local TO_STORE="`grep "^$SPELL:$1:providedby:optional:.*:.*$" $DEPENDS_STATUS | cut -d':' -f 5 | tail -1`"
-
-    if [ -z "$TO_STORE" ]; then
-
-      if [[ "$ASK_NONE" == true ]]; then
-        message -n "$SPELL_COLOR$SPELL$DEFAULT_COLOR optionally needs some "
-        message "$SPELL_COLOR$1$DEFAULT_COLOR. ($reasontext)"
-      else
-        message -n "$SPELL_COLOR$SPELL$DEFAULT_COLOR needs some "
-        message "$SPELL_COLOR$1$DEFAULT_COLOR as a requirement."
-      fi
-
-      local INST_PROV_LIST temp spell
-      local CANDIDATES=$( find_providers $1 )
-
-      for spell in $CANDIDATES; do
-          if spell_installed $spell || spell_held $spell; then
-              [[ $INSTALLED == false ]] && INST_PROV="$spell"
-              INSTALLED=true
-          fi
-
-          if ! spell_exiled $spell; then
-              temp="$temp $spell"
-          fi
-      done
-
-      if [[ $INSTALLED == true ]]; then
-          message -n "$SPELL_COLOR$1$DEFAULT_COLOR is already provided " 
-          message   "by $SPELL_COLOR$INST_PROV$DEFAULT_COLOR"
-          if query "Do you want to use that?" "y"; then
-              eval ''$returnvar'='$INST_PROV''
-              return 0
-          fi 
-      fi
-
-      if [[ ! $temp ]]; then
-          echo "Cannot satisfy requirements for $1"
-          return 1
-      fi
-
-      if [[ $ASK_NONE == true ]]; then
-          select_list "TO_STORE" "[none]" $temp
-      else
-          select_list "TO_STORE" $temp
-      fi
+    if [[ $optional == true ]] ; then
+      message -n "$SPELL_COLOR$SPELL$DEFAULT_COLOR optionally needs some "
+      message "$SPELL_COLOR$1$DEFAULT_COLOR. ($reasontext)"
+    else
+      message -n "$SPELL_COLOR$SPELL$DEFAULT_COLOR needs some "
+      message "$SPELL_COLOR$provname$DEFAULT_COLOR as a requirement."
     fi
-    eval ''$returnvar'='$TO_STORE''
+
+    local INST_PROV_LIST temp spell
+    local CANDIDATES=$( find_providers $provname )
+
+    for spell in $CANDIDATES; do
+        if spell_installed $spell || spell_held $spell; then
+            [[ $INSTALLED == false ]] && INST_PROV="$spell"
+            INSTALLED=true
+        fi
+
+        if ! spell_exiled $spell; then
+            temp="$temp $spell"
+        fi
+    done
+
+    if [[ $INSTALLED == true ]]; then
+        message -n "$SPELL_COLOR$provname$DEFAULT_COLOR is already provided " 
+        message   "by $SPELL_COLOR$INST_PROV$DEFAULT_COLOR"
+        if query "Do you want to use that?" "y"; then
+            eval ''$returnvar'='$INST_PROV''
+            return 0
+        fi 
+    fi
+
+    if [[ ! $temp ]]; then
+        echo "Cannot satisfy requirements for $provname"
+        return 1
+    fi
+
+    local selected
+
+    if [[ $optional == true ]]; then
+        select_list "selected" "[none]" $temp
+    else
+        select_list "selected" $temp
+    fi
+
+    eval ''$returnvar'='$selected''
+
 }
 
-function work_depends()
+function work_depends_provider()
 {
+
+  debug "libdepends" "$FUNCNAME - $@"
+
+  local status=()
+  
+  # See if there are preferences already.
+  # Example: rxvt-unicode:xfree86(X11-LIBS):on:required::
+  explode "$(search_depends_status "$SPELL" ".*($1)")" ":" "status"
+
+  local provider=${status[1]%(*}    # Name of spell which provides $1
+
+  if [[ $RECONFIGURE || ! $provider ]] ; then
+    select_provider "provider" "$1"
+  fi
+
+  private_common_depends "$provider($1)" "on" "required" "$2" "$3"
+
+}
+
+function work_depends_spell()
+{
+
+  debug "libdepends" "$FUNCNAME - $@"
 
   if spell_exiled $1 ; then
   	hash_put $CANNOT_CAST_HASH "$1" "Exiled"
     message "${SPELL_COLOR}$1${DEFAULT_COLOR} has been exiled!"
     return 1
   fi
+
   private_common_depends "$1" "on" "required" "$2" "$3"
+
 }
 
+#---------------------------------------------------------------------
+## @param  provider name
+## @param  addition to OPTS if enabled
+## @param  addition to OPTS if disabled
+## @param  description
+## Handles optional dependency on a provider.
+#---------------------------------------------------------------------
+function work_optional_depends_provider()
+{
 
-function work_optional_depends()
+  debug "libdepends" "$FUNCNAME - $@"
+
+  local install="off"
+  local status=()
+  
+  # See if there are preferences already.
+  # Example when enabled:
+  #  GD:xfree86(X11-LIBS):on:optional:-options=JPG,FT,XPM:-options=JPG,FT
+  # Example when disabled:
+  #  GD:(X11-LIBS):off:optional:-options=JPG,FT,XPM:-options=JPG,FT
+  explode "$(search_depends_status "$SPELL" ".*($1)")" ":" "status"
+
+  local provider=${status[1]%(*}    # Name of spell which provides $1
+
+  if [[ $RECONFIGURE || ! ${status[2]} ]] ; then
+
+    select_provider "provider" "$1" "$4" "optional"
+
+    if [[ $provider == "[none]" ]] ; then
+      provider=""       # User selected [none]. Disable dependency
+    elif ! spell_installed $provider && ! spell_held $provider ; then
+      if query "Do you want to cast ${SPELL_COLOR}$provider${DEFAULT_COLOR}?" n
+      then install="on"
+      else provider=""
+      fi
+    else
+      install="on"
+    fi
+  elif [[ ${status[2]} == on ]] ; then
+    install="on"
+  fi
+
+  if [[ $provider == "" ]] ; then
+    install=off
+  fi
+
+  private_common_depends "$provider($1)" "$install" "optional" "$2" "$3"
+
+}
+
+#---------------------------------------------------------------------
+## @param  spell name
+## @param  addition to OPTS if enabled
+## @param  addition to OPTS if disabled
+## @param  description
+## Handles optional dependency on a spell.
+#---------------------------------------------------------------------
+function work_optional_depends_spell()
 {
 
   debug "libdepends" "$FUNCNAME - $@"
   
-  local NOQUESTION=false
-
-  if [[ "$1" == "no_question" ]]; then
-		shift;
-		NOQUESTION=true
-  fi
-	
   if spell_exiled $1 ; then 
     message "${SPELL_COLOR}$1${DEFAULT_COLOR} has been exiled!"
-   	hash_put $CANNOT_CAST_HASH "$1" "Exiled"
+    hash_put $CANNOT_CAST_HASH "$1" "Exiled"
     return 1
   fi
   
@@ -404,29 +473,21 @@ function work_optional_depends()
   #See if there are preferences already
   #example: icewm:imlib:off:optional:--with-imlib:--with-xpm
   explode "$(search_depends_status "$SPELL" "$1")" ":" "status" 
-	
-  if [[ $RECONFIGURE ]] || ! [[ ${status[2]} && ${status[2]} != "providedby" ]] ; then
 
-		if [[ $NOQUESTION == false ]]; then
-			message "${SPELL_COLOR}$1${DEFAULT_COLOR} is an optional dependency for ${SPELL_COLOR}$SPELL${DEFAULT_COLOR} ($4)"
+  if [[ $RECONFIGURE || ! ${status[2]} ]] ; then
 
-			if spell_installed $1 || spell_held $1 ; then
-				query "Do you want to use ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "y" && 
-					install="on"
-			else
-				query "Do you want to cast ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "n" && 
-					install="on"
-      fi
-		else
-			if codex_does_spell_exist $1 >/dev/null; then
-				install="on"
-			else # in this case, it's a provider and they said [none]
-				install="providedby"
-			fi
-  	fi
+    message -n "${SPELL_COLOR}$1${DEFAULT_COLOR} is an optional "
+    message "dependency for ${SPELL_COLOR}$SPELL${DEFAULT_COLOR} ($4)"
 
+    if spell_installed $1 || spell_held $1 ; then
+      query "Do you want to use ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "y" && 
+        install="on"
+    else
+      query "Do you want to cast ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "n" && 
+        install="on"
+    fi
   elif [[ ${status[2]} == on ]] ; then
-		install="on"
+    install="on"
   fi
 
   private_common_depends "$1" "$install" "optional" "$2" "$3"
@@ -493,7 +554,9 @@ function private_common_depends()
   add_depends "$SPELL" "$@"
   
   if [[ $2 == on ]] ; then
-    NEW_DEPENDS=( "${NEW_DEPENDS[@]}" $1 )
+    # ${1%(*} = spell name (strips potential provider name)
+    local spell_name=${1%(*}
+    NEW_DEPENDS=( "${NEW_DEPENDS[@]}" $spell_name )
   fi
   
   return 0
@@ -600,7 +663,8 @@ function private_compute_installed_depends()
 
 	# Fill in a temporary hashtable for spells that have dependancies
 	# not all dependencies are installed
-	eval $(awk -F : '$3=="on"{ spells[$1]=spells[$1]" "$2" "; }
+	# gsub(/(.*)/, "", $1) is for removing a possible provider name
+	eval $(awk -F : '$3=="on"{ spells[gsub(/(.*)/, "", $1)]=spells[$1]" "$2" "; }
 	END{
 		for(spell in spells) { 
 			printf("hash_put \"pcid\" \"%s\" \" %s \";\n", spell, spells[spell]); 
