devel => test for 1.13.0

diff --git a/var/lib/sorcery/modules/libdepends b/var/lib/sorcery/modules/libdepends
--- a/var/lib/sorcery/modules/libdepends
+++ b/var/lib/sorcery/modules/libdepends
@@ -163,6 +163,27 @@ function run_depends()
     persistent_save
   fi
 }
+
+#---------------------------------------------------------------------
+## Run a spell's UP_TRIGGERS if it exists
+## @param Spell
+#---------------------------------------------------------------------
+function run_up_triggers() {
+  local SPELL=$1
+  debug "cast" "run_up_triggers() - SCRIPT_DIRECTORY = $SCRIPT_DIRECTORY"
+ 
+  local PROTECT_SORCERY=yes
+  if  [  -x  $SCRIPT_DIRECTORY/UP_TRIGGERS ];  then
+    message  "${SPELL_COLOR}${SPELL}${DEFAULT_COLOR}" \
+             "${CHECK_COLOR}checking for reverse triggers...${DEFAULT_COLOR}"
+    # we need &&'s to preserve the proper return code (persistant_save
+    # will probably succeed even if PREPARE fails)
+    persistent_load &&
+    . $SCRIPT_DIRECTORY/UP_TRIGGERS &&
+    persistent_save
+  fi
+  
+}
 ######################END CALLS TO OUTSIDE WORLD########################
 
 
@@ -177,7 +198,7 @@ function run_depends()
 function compute_installed_depends() {
   #$1==hash table to fill
   local hash=$1
-  touch $DEPENDS_STATUS $SPELL_STATUS
+  touch $DEPENDS_STATUS $SPELL_STATUS &>/dev/null
 
   # From here forward $1 and $2 are only used to refer to awk variables
 
@@ -207,6 +228,7 @@ function compute_installed_depends() {
 function compute_reverse_installed_depends() {
   #$1==hash table to fill
   local hash=$1
+  touch $DEPENDS_STATUS $SPELL_STATUS &>/dev/null
 
   # From here forward $1 and $2 are only used to refer to awk variables
 
@@ -263,20 +285,20 @@ function compute_uninstalled_depends()
 
   PRETEND_NOT_INSTALLED=" $@ "
 
-  local i
+  local _idx
   
   # All specified spells are assumed to be not installed, or else -c and -r 
   # would have to be specified all the time.
   
-  for (( i=0 ; i<${#spells[*]} ; i++ )) ; do
-    if [[ ! `hash_get depends_looked_at ${spells[$i]}` ]]; then
-      if ! private_run_depends ${spells[$i]} ; then
+  for (( _idx=0 ; _idx<${#spells[*]} ; _idx++ )) ; do
+    if [[ ! `hash_get depends_looked_at ${spells[$_idx]}` ]]; then
+      if ! private_run_depends ${spells[$_idx]} ; then
         # i dont know if this will work, but it will have to suffice
-        private_remove_dependees ${spells[$i]}
+        private_remove_dependees ${spells[$_idx]}
       fi
     else
-      debug "libdepends" "already looked at ${spells[$i]}, skipping"
-   fi
+      debug "libdepends" "already looked at ${spells[$_idx]}, skipping"
+    fi
   done
   # we no longer need this, no sense in keeping it around
   hash_unset depends_looked_at
@@ -296,14 +318,22 @@ function private_run_depends()
   debug "libdepends" "$FUNCNAME - $*"
   local SPELL=$1
   local NEW_DEPENDS=""
+  local triggerees=""
   local spell_depends
   hash_put "depends_looked_at" "$SPELL" "start"
+
+  # move this up to compute_uninstalled_depends?
+  # this is a list of all spells basesystem depends on it is used to
+  # avoid loops with the "everything depends on basesystem" feature
+  local base_deps
+  base_deps=$(search_depends_status $DEPENDS_STATUS basesystem|cut -f2 -d:)
 
   
   # We only need to run the stuff if we are going to be casting.
   # It only needs to be added to the casting hash table if we are
   # really casting it
   if private_should_cast $SPELL ; then
+
     # this cant go in private_should_cast because then the dependee wont
     # have a chance at being fixed, ideally we should check in 
     # depends/optional_depends and fail there
@@ -324,8 +354,11 @@ function private_run_depends()
     run_configure $SPELL          &&
     run_other $SPELL              &&
     run_depends $SPELL            && 
+    run_up_triggers $SPELL        && 
+
     # possibly recast things that depend on us if option is set (-B)
     private_upward_depends $SPELL &&
+    private_add_triggerees        &&
     private_add_depends           ||
     { debug "libdepends" "$FUNCNAME: false inside if." ; return 1; }
     # no point in keeping the file around if its empty...
@@ -365,6 +398,10 @@ function private_should_cast()
     return 0
   elif echo "${UP_DEPENDS[*]}" | grep -q "\<$1\>" ; then
     # if someone has determined this is an upward depend (-B)
+    return 0
+  elif echo "${TRIGGEREES[*]}" | grep -q "\<$1\>" ; then
+    # if its being triggered we need to look at it, despite its
+    # installed status
     return 0
   elif spell_installed $1 ; then
     # spell is installed and no -R or -B, so dont cast
@@ -790,9 +827,15 @@ function work_optional_depends_spell()
     explode "$(search_depends_status $DEPENDS_STATUS "$SPELL" "$1")" ":" "status"
     if [[ ${status[2]} ]] ; then
       # ah there are! use them
-      message "${SPELL_COLOR}${SPELL}${DEFAULT_COLOR}" \
-              "${CHECK_COLOR}optionally depends on" \
-              "${SPELL_COLOR}${1}${DEFAULT_COLOR}"
+      if [[ ${status[2]} == "on" ]] ; then
+        message "${SPELL_COLOR}${SPELL}${DEFAULT_COLOR}" \
+                "${CHECK_COLOR}optionally depends on" \
+                "${SPELL_COLOR}${1}${DEFAULT_COLOR}"
+      else
+        message "${SPELL_COLOR}${SPELL}${DEFAULT_COLOR}" \
+                "${CHECK_COLOR}has a disabled optional depends on" \
+                "${SPELL_COLOR}${1}${DEFAULT_COLOR}"
+      fi
       private_common_depends "$1" "${status[2]}" "optional" "$2" "$3"
       return 0
     fi
@@ -928,6 +971,45 @@ function select_provider()
 }
 
 #---------------------------------------------------------------------
+## @param Target of the trigger
+## @param Action to execute (cast_self, check_self, etc).
+##
+## Create a trigger on ourself effecting the target spell,
+## shorthand for putting a TRIGGERS file in the target spell.
+#---------------------------------------------------------------------
+function real_up_trigger() {
+  message  "${SPELL_COLOR}${SPELL}${DEFAULT_COLOR}" \
+           "${CHECK_COLOR}triggers a" \
+           "${SPELL_COLOR}${2}${DEFAULT_COLOR}" \
+           "${CHECK_COLOR}on${DEFAULT_COLOR}" \
+           "${SPELL_COLOR}${1}${DEFAULT_COLOR}"
+  private_up_trigger $SPELL "$1" "$2"
+}
+
+#---------------------------------------------------------------------
+## @param Current spell
+## @param Target target of the trigger
+## @param Action to execute (cast_self, check_self, etc).
+##
+## Register a trigger, when $SPELL is cast, a $ACTION is executed
+## on $TARGET
+#---------------------------------------------------------------------
+function private_up_trigger() {
+  local SPELL=$1
+  local TARGET=$2
+  local ACTION=$3
+  # this maps triggerers to their trigerees
+  # perl -> cast_self:perl_module
+  hash_append trg_f_hash  $SPELL "$TARGET:$ACTION" $'\n' &&
+  # this maps trigerees to triggerers
+  # cast_self:perl_module -> perl
+  hash_append trg_r_hash  "$TARGET:$ACTION" " $SPELL "
+  echo $NEW_DEPENDS | grep -q "$TARGET" || 
+  NEW_DEPENDS=( ${NEW_DEPENDS[*]} $spell)
+  triggerees=( ${triggerees[*]} $TARGET )
+}
+
+#---------------------------------------------------------------------
 ## all the depends callbacks eventually bottom out here
 ## if a spell depends or doesnt depend on some other spell
 ## @param Spell
@@ -935,7 +1017,7 @@ function select_provider()
 #---------------------------------------------------------------------
 function private_common_depends()
 {
-  debug "libdepends" "$FUNCNAME - $@"
+  debug "libdepends" "$FUNCNAME - $SPELL - $@"
   add_depends $spell_depends "$SPELL" "$@"
   
   if [[ $2 == on ]] ; then
@@ -948,17 +1030,89 @@ function private_common_depends()
 }
 
 #---------------------------------------------------------------------
+## Default trigger checking function. Asks user if they want to
+## run the trigger.
+#---------------------------------------------------------------------
+function default_trigger_check() {
+  message  "${SPELL_COLOR}${SPELL}${DEFAULT_COLOR}" \
+           "${CHECK_COLOR}triggers a" \
+           "${SPELL_COLOR}${ACTION}${DEFAULT_COLOR}" \
+           "${CHECK_COLOR}on${DEFAULT_COLOR}" \
+           "${SPELL_COLOR}${TARGET}${DEFAULT_COLOR}"
+  query "Run the trigger?" y
+}
+
+#---------------------------------------------------------------------
+## Inspects each trigger, asks the user if they want to run it.
+#---------------------------------------------------------------------
+function private_add_triggerees() {
+
+  # add the spells that we trigger to the $spells list
+  # having duplicate items is okay
+  local ACTION TARGET
+  local running_trigger
+
+  # run the trigger check file
+  # this is made into a sub-function just to reduce duplication...
+  function private_add_triggerees_sub1() {
+    running_trigger=0
+    persistent_load
+    if test -x $SCRIPT_DIRECTORY/TRIGGER_CHECK; then
+      source $SCRIPT_DIRECTORY/TRIGGER_CHECK
+    else
+      default_trigger_check
+    fi
+    running_trigger=$?
+    persistent_save
+    if [[ $running_trigger == 0 ]] ; then
+      private_up_trigger "$SPELL" "$TARGET" "$ACTION"
+    fi
+  }
+
+  # frontend to help with calling the trigger check file
+  function private_add_triggerees_sub2() {
+    local ACTION=$1
+    private_add_triggerees_sub1
+  }
+
+  for ACTION in cast_self check_self dispel_self run_script; do
+    for TARGET in $(get_triggerees $SPELL on_cast $ACTION); do
+      if [[ $ACTION == run_script ]] ; then
+        iterate private_add_triggerees_sub2 $'\n' \
+                          "$(get_run_script_triggers $SPELL on_cast $TARGET)"
+      else
+        private_add_triggerees_sub1
+      fi
+    done
+  done
+  return 0
+}
+
+
+#---------------------------------------------------------------------
 ## Adds the dependency to the hastable 
 #---------------------------------------------------------------------
 function private_add_depends()
 {
   debug "libdepends" "$FUNCNAME: SPELL=$SPELL, NEW_DEPENDS=${NEW_DEPENDS[*]}"
   hash_put "$CAST_HASH" "$SPELL" "${NEW_DEPENDS[*]}"
+
   for child in ${NEW_DEPENDS[*]}; do
     hash_append "$BACK_CAST_HASH" "$child" "$SPELL"
   done
-  
+
+  # force implied basesystem dependency in the depends tree
+  if [[ $FORCE_BASESYSTEM_DEPENDS == on ]] &&
+     [[ $SPELL != basesystem ]] &&
+     ! echo $base_deps| grep -q $SPELL; then
+    hash_append "$CAST_HASH" "$SPELL" "basesystem"
+    hash_append "$BACK_CAST_HASH" "basesystem" "$SPELL"
+  fi
+
   spells=( ${spells[*]} ${NEW_DEPENDS[*]} )
+
+  TRIGGEREES=( ${TRIGGEREES[*]} ${triggerees[*]} )
+  spells=( ${spells[*]} ${triggerees[*]} )
 
   hash_put "depends_looked_at" "$SPELL" "done"
 
@@ -1025,88 +1179,9 @@ function show_depends()
       
     }
     
-    iterate "ld99" $'\n' `grep  ":$DEP_SPELL\(([^:]*)\)\?:" $DEPENDS_STATUS`
+    iterate "ld99" $'\n' "$(grep  ":$DEP_SPELL\(([^:]*)\)\?:" $DEPENDS_STATUS)"
 
   fi
-}
-
-#---------------------------------------------------------------------
-# this needs to go away :-/
-#---------------------------------------------------------------------
-function satisfy_depends()
-{
-
-  debug "libdepends" "Running satisfy_depends() on $SPELL"  
-  local DEP
- 
-  unset  OPTS
-
-  # some spells apply changes to OPTS directly
-  run_spell_config
-
-  local LINE=''
-  search_depends_status $DEPENDS_STATUS "$SPELL" | while read LINE; do
-
-    debug "libdepends" "satisfy_depends() - $LINE"
-
-    # line format is:
-    #  spell:dependency(provider):status:something:on-opts:off=opts
-    DEP=()
-    explode "$LINE" ":" "DEP"
-    DEP[1]=${DEP[1]%(*}   # Strip possible provider name
-
-    # If dependency name is "" then don't bother with the rest of this loop.
-    if [[ ! ${DEP[1]} ]] ; then
-      continue
-    fi
-
-    # First, see if the spell exists.
-    DEP_SPELL_LOCATION=`codex_find_spell_by_name ${DEP[1]}`
-    if  [  -z  "$DEP_SPELL_LOCATION"  ];  then
-      message  "${PROBLEM_COLOR}Unable to find previously configured"  \
-               "dependency ${SPELL_COLOR}'${DEP[1]}'${PROBLEM_COLOR}"
-      message  "in grimoire.  Removing spell from cached depends."     \
-               "${DEFAULT_COLOR}"
-      remove_depends_status  "$SPELL"  "${DEP[1]}"
-    else
-
-      #Second, am I trying to cast --fix or is this just a normal cast?
-      if  [[  $FIX  ]] ; then
-      
-	#Third, if it's a fix, and the dependency is on, cast --fix it
-        if  [[ ${DEP[2]} == on ]] 
-	then  debug "libdepends" "cast  $FIX  ${DEP[1]}" && cast  $FIX  ${DEP[1]}
-	else debug "libdepends" "Fix=$FIX, and DEP[2]=${DEP[2]}"
-        fi
-
-      #(second) It's a normal cast, and this may need to be cast
-      elif  [[  ${DEP[2]}  ==  on  ]]; then
-        #
-        # Spell must be installed or help up to this point (this is a guard fence)
-        #
-        if  !  spell_installed  ${DEP[1]}  &&
-            !  spell_held       ${DEP[1]}
-        then
-          message "One of the dependencies of ${DEP[0]} failed to cast."
-          message "You should try to cast ${DEP[1]} manualy."
-          message "Failed to cast ${DEP[1]}. I will have trouble casting ${DEP[0]}."
-          return 1          
-        fi
-        #
-        # End of guard fence
-        #
-      fi
-    fi
-
-  done
-
-  #
-  # TODO: Do something about exiled spells so that they've got `off'
-  #       in DEPENDS_STATUS file, or something else do improve this
-  #
-  local OPTS_DEPENDS=$(get_depends_options $DEPENDS_STATUS "$SPELL")
-  OPTS="$OPTS $OPTS_DEPENDS"
-  debug 'libdepends' "satisfy_depends() - final OPTS=$OPTS"
 }
 
 #---------------------------------------------------------------------
diff --git a/var/lib/sorcery/modules/libgpg b/var/lib/sorcery/modules/libgpg
--- a/var/lib/sorcery/modules/libgpg
+++ b/var/lib/sorcery/modules/libgpg
@@ -23,14 +23,15 @@
 ##    5: no keyring
 ##  200: gpg isnt installed
 ##
-## @stdout annoying message instructing user to install gnupg if its
-##         not installed
+## @stdout message when gpg is not installed
+##
 #---------------------------------------------------------------------
-function gpg_verify_signature() { # $1 sig $2 file $3 pubring
+function gpg_verify_signature() { # $1 sig $2 file $3 pubring $4 algo var
 
   local signature=$1
   local file=$2
   local keyring=$3
+  local algo=""
 
   test -f $signature || return 3
   test -f $file || return 4
@@ -49,18 +50,20 @@ function gpg_verify_signature() { # $1 sig $2 file $3 pubring
             "should be done for you on a system update.${DEFAULT_COLOR}"
     return 200
   else
-    gpg --no-default-keyring  \
-        --always-trust        \
-        --keyring $keyring    \
-        --batch               \
-        --verify              \
-        $signature            \
-        $file 2> /dev/null ||
+    algo=$(gpg --no-default-keyring  \
+               --always-trust        \
+               --keyring $keyring    \
+               --batch               \
+               --verbose             \
+               --verify              \
+               $signature            \
+               $file 2>&1 | grep 'digest algorithm' | awk '{ print $NF }' | 
+               tr A-Z a-z || return 1 ) || 
     return 1      # error out if verification fails.
   fi
+  [ ! -z "$4" ] && eval "$4=\"$algo\""
   return 0
 }
-
 
 #---------------------------------------------------------------------
 ## Get the sorcery gpg key file associated with a branch
@@ -133,6 +136,46 @@ function gpg_verify_grimoire() {
   gpg_verify_common $FILENAME $SOURCE_URL $gpg_pub_key grimoire $SIGNATURE
 }
 
+
+
+function verify_grimoire_tree() {
+  local grimoire_name=$1
+  local grimoire_dir=$2
+
+  if [[ "$GPG_VERIFY_GRIMOIRE" != on ]] ; then
+    return 253
+  fi
+
+  local gpg_pub_key=$(gpg_get_grimoire_key $grimoire_name)
+  if test -z $gpg_pub_key && test -f $gpg_pub_key ; then
+    message "No keyring found! (maybe you need to cast sorcery-pubkeys?)"
+    return 254
+  fi
+
+  manifest=$grimoire_name.manifest.$GRIMOIRE_MANIFEST_ALGORITHM
+  manifest_url=${CODEX_MANIFEST_URL}/$manifest
+
+  pushd $TMP_DIR >/dev/null || return 1
+
+  local manifest_target manifest_type
+  url_download $manifest $manifest_url "" manifest_target manifest_type
+  #check the success of the download
+  if [ $? != 0 ] || [[ "$manifest_type" != file ]] ; then
+    message "Error downloading manifest..."
+    return 1
+  fi
+
+  gpg_verify_common $manifest $CODEX_MANIFEST_URL $gpg_pub_key "grimoire manifest"
+  if ! gpg_user_query $?; then
+    return 2
+  fi
+
+  popd >/dev/null
+
+  verify_grimoire_against_manifest "$grimoire_dir" "$TMP_DIR/$manifest" \
+                                   "$GRIMOIRE_MANIFEST_ALGORITHM"
+}
+
 #---------------------------------------------------------------------
 ## Verify a sorcery tarball's gpg signature
 ## @param file on local disk to verify
@@ -166,7 +209,7 @@ function gpg_verify_sorcery() {
     message "No keyring found! (maybe you need to cast sorcery-pubkeys?)"
     return 254
   fi
-  gpg_verify_common $FILENAME $SOURCE_URL $gpg_pub_key sorcery $SIGNATURE
+  gpg_verify_common "$FILENAME" "$SOURCE_URL" "$gpg_pub_key" "sorcery" "$SIGNATURE"
 }
 
 #---------------------------------------------------------------------
@@ -197,13 +240,18 @@ function gpg_verify_common() {
   local SOURCE=$(basename $FILENAME)
 
   local SIG_FILE=${SOURCE}.${GPG_SIG_EXT}
+  pushd $TMP_DIR &>/dev/null || 
+  { message "Failed to cd to $TMP_DIR!!"; return 2;}
   if test -z "$SIGNATURE" ; then
     local SIG_URL=$SOURCE_URL/$SIG_FILE
-    echo "$SIG_FILE $SIG_URL" |
-    download_files "for $REASON verification" "$TMP_DIR" "no" "neither" || {
+    local gpg_target gpg_type
+    url_download "$SIG_FILE" "$SIG_URL" "file" gpg_target gpg_type &&
+    [[ $gpg_type == file ]] ||
+    {
       message "Failed to get gpg signature! verification is impossible"
       return 255
     }
+    [[ "$gpg_target" != $SIG_FILE ]] && mv "$gpg_target" "$SIG_FILE"
   else
     cp $SIGNATURE $TMP_DIR/$SIG_FILE
   fi
@@ -211,6 +259,7 @@ function gpg_verify_common() {
   gpg_verify_signature $TMP_DIR/$SIG_FILE $FILENAME $gpg_pub_key
   rc=$?
   rm $TMP_DIR/$SIG_FILE
+  popd &>/dev/null
 
   return $rc
 }
@@ -234,22 +283,146 @@ function gpg_user_query() {
     message "${MESSAGE_COLOR}gpg verification is disabled${DEFAULT_COLOR}"
   else
     message "${PROBLEM_COLOR}Failure to verify gpg signature${DEFAULT_COLOR}"
-
-    if [[ "$3" == "grimoire" ]] ; then
-      if [[ "$2" == devel ]] || [[ "$2" == test ]] || [[ "$2" == stable ]] ||
-         [[ "$2" == z-rejected ]] || [[ "$2" == games ]] ; then
+    case "$3" in
+      grimoire)
+        if list_find "$GPG_GRIMOIRE_LIST" $2 > /dev/null 2>&1 ; then
+          query "Continue anyway?" n || return 1
+        else
+          # if its not one of our grimoires may want the default to be y
+          query "Continue anyway?" y || return 1
+        fi
+        ;;
+      spell)
+        unpack_file_user_query $rc || return 1
+        ;;
+      *)
         query "Continue anyway?" n || return 1
-      else
-        # if its not one of our grimoires may want the default to be y
-        query "Continue anyway?" y || return 1
-      fi
-    else
-      query "Continue anyway?" n || return 1
-    fi
+        ;;
+    esac
   fi
   return 0
 }
 
+
+#---------------------------------------------------------------------
+## @param algorithm to use
+## @param file to get hashsum of
+## @out output is exactly the same format as md5sum/sha1sum, just with
+## a different hashsum. "hashsum<space><space>filename". The hashsum is
+## printed with all lowercase letters.
+##
+## This assumes that the caller has already verified that gpg is
+## installed and supports the specified hash function.
+##
+#---------------------------------------------------------------------
+function gpg_hashsum() {
+  local algorithm=$1
+  local file=$2
+  gpg --print-md "$algorithm" "$file"| tr -d '\n '  |cut -f2 -d:|
+                                       tr 'A-F' 'a-f'|tr -d '\n'
+  echo "  $file"
+}
+
+#---------------------------------------------------------------------
+## @out All the hash algorithms supported by gpg, algorithms printed in
+## lower case.
+##
+## This assumes the caller has already verified that gpg is installed.
+#---------------------------------------------------------------------
+function gpg_get_hashes() {
+  gpg --version 2> /dev/null | grep '^Hash' | awk -F: '{ print $2 }' | tr , ' ' | tr 'A-Z' 'a-z'
+}
+
+#---------------------------------------------------------------------
+## Verify a tree against a manifest file
+## @param directory to verify
+## @param manifest file, the format is like what the md5sum tool would
+##        produce
+## @param algorithm to use, this can be anything supported by gpg
+## @param regular expression of files to ignore
+#---------------------------------------------------------------------
+function verify_against_manifest() {
+  local dir=$1
+  local manifest=$2
+  local algorithm=$3
+  local ignore=$4
+  local base=$(basename $dir)
+  local real_list=$TMP_DIR/$base
+  local missing=$TMP_DIR/missing.$base
+  local rc=0
+
+  message "Validating tree at $dir with $manifest"
+  local manifest_format=$(echo $manifest|awk -F. '{print $NF}')
+
+  pushd $dir > /dev/null || return $?
+  find . -type f > $real_list
+  { cat $real_list $real_list ; awk '{print $NF}' $manifest ; } |
+  sort | uniq -c | grep -v '^ *3' | grep -v "$ignore" > $missing
+  NO_TREE=$(grep "^ *1" $missing|sed 's/^ *1 //')
+  if [[ $NO_TREE ]] ; then
+    message "${PROBLEM_COLOR}The following exist only in the manifest" \
+            "and are missing from the tree!${DEFAULT_COLOR}"
+    echo "$NO_TREE"|$PAGER
+    let rc+=1
+  fi
+  NO_MANIFEST=$(grep "^ *2" $missing|sed 's/^ *2 //')
+  if [[ $NO_MANIFEST ]] ; then
+    message "${PROBLEM_COLOR}The following exist only in the tree" \
+            "and are missing from the manifest!${DEFAULT_COLOR}"
+    echo "$NO_MANIFEST"|$PAGER
+    let rc+=1
+  fi
+  local hash r
+  while read hashsum file; do
+    local hash=$(gpg_hashsum $algorithm $file 2>/dev/null|cut -f1 -d' ')
+    r=$?
+    if [[ $hash != $hashsum ]] || [[ $r != 0 ]]; then
+      NOT_OK=( $NOT_OK "$file" )
+    fi
+  done < $manifest
+
+  if [[ $NOT_OK ]] ; then
+    message "${PROBLEM_COLOR}The following have bad checksums${DEFAULT_COLOR}"
+    echo "$NOT_OK"
+    let rc+=1
+  fi
+  popd $dir > /dev/null
+  return $rc
+}
+
+#---------------------------------------------------------------------
+## Verify a grimoire tree and ignore files sorcery adds post-download
+#---------------------------------------------------------------------
+function verify_grimoire_against_manifest() {
+  verify_against_manifest $1 $2 $3 \
+                          '^ *2 \./\(GRIMOIRE\|codex\.index\|provides\.index\)$'
+}
+
+#---------------------------------------------------------------------
+## Ask the user what they want to do if verification of a grimoire tree
+## fails.
+#---------------------------------------------------------------------
+function grimoire_tree_user_query() {
+  local grimoire_name=$1
+  message "${PROBLEM_COLOR}Verification of the grimoire" \
+          "tree ${DEFAULT_COLOR}${SPELL_COLOR}$grimoire_name" \
+          "${DEFAULT_COLOR}${PROBLEM_COLOR}failed!"
+  message "What would you like to do?${DEFAULT_COLOR}"
+  local choice
+  select_list choice 0 "set aside" "remove" "ignore"
+  case "$choice" in
+    "set aside") local tgt=$grimoire_name.$(date +%Y%m%d%H%M).corrupt
+                 message "moving grimoire to $tgt"
+                 mv $grimoire_name $tgt
+                 scribe_remove $grimoire_name &>/dev/null
+                 ;;
+         remove) rm -rf $grimoire_name
+                 scribe_remove $grimoire_name &>/dev/null;;
+         ignore) return 0 ;;
+  esac
+  return 1
+}
+ 
 #---------------------------------------------------------------------
 ## This software is free software; you can redistribute it and/or modify
 ## it under the terms of the GNU General Public License as published by
