made depends = requires + depends and      optional_depends = optional_depends + "optional_requires"      and changed their output..

diff --git a/var/lib/sorcery/modules/libdepends b/var/lib/sorcery/modules/libdepends
--- a/var/lib/sorcery/modules/libdepends
+++ b/var/lib/sorcery/modules/libdepends
@@ -228,7 +228,7 @@ function compute_depends()
 #  else
 #    private_remove_installed_spells
 #  fi
-  
+
   for (( i=0 ; i<${#SPELLS[*]} ; i++ )) ; do
     private_run_depends ${SPELLS[$i]}
   done
@@ -242,7 +242,103 @@ function compute_depends()
 
 }
 
+
 function depends()
+{
+    local INST
+    if ! codex_does_spell_exist $1 &> /dev/null; then
+        message -n "$SPELL_COLOR$SPELL$DEFAULT_COLOR needs some "
+        message "$SPELL_COLOR$1$DEFAULT_COLOR as a requirement."
+        select_provider "INST" "$@"
+        [[ $? ]]     || return 1
+        [[ ! $INST ]] && return 1
+        shift
+        real_depends "$INST" "$@"
+
+    else
+        real_depends      "$@"
+    fi
+}
+
+function requires() { #deprecated, martin 20030906
+    depends "$@"
+}
+
+function optional_depends()
+{
+    local INST
+
+    if ! codex_does_spell_exist $1 &> /dev/null; then
+
+        message -n "$SPELL_COLOR$SPELL$DEFAULT_COLOR optionally needs some "
+        message "$SPELL_COLOR$1$DEFAULT_COLOR. ($4)"
+
+        select_provider "INST" "[none]" "$@"
+        [[ $? ]] || return 1
+        [[ ! $INST ]] && return 1
+        [[ $INST == "[none]" ]] && return 0
+        shift
+        real_optional_depends "no_question" "$INST $@"
+    else
+        real_optional_depends "$@" 
+    fi
+}
+
+
+#---------------------------------------------------------------------
+##=item select_provider <return_var> <elements,..>
+## 
+## gives the user some nice select list and puts the selected
+## spell in return_var
+##
+#---------------------------------------------------------------------
+function select_provider()
+{
+    local INSTALLED=false
+    local returnvar=$1
+    shift
+    if [[ $1 == '[none]' ]]; then
+        local ASK_NONE=true
+        shift
+    fi
+
+    local INST_PROV_LIST temp spell TO_STORE
+    local CANDIDATES=$( find_providers $1 )
+
+    for spell in $CANDIDATES; do
+        if spell_installed $spell || spell_held $spell; then
+            [[ $INSTALLED == false ]] && INST_PROV="$spell"
+            INSTALLED=true
+        fi
+
+        if ! spell_exiled $spell; then
+            temp="$temp $spell"
+        fi
+    done
+
+    if [[ $INSTALLED == true ]]; then
+        message -n "$SPELL_COLOR$1$DEFAULT_COLOR is already provided" 
+        message   "by $SPELL_COLOR$INST_PROV$DEFAULT_COLOR"
+        if query "Do you want to use that?" "y"; then
+            eval ''$returnvar'='$INST_PROV''
+            return 0
+        fi 
+    fi
+
+    if [[ ! $temp ]]; then
+        echo "Cannot satisfy requirements for $1"
+        return 1
+    fi
+
+    if [[ $ASK_NONE == true ]]; then
+        select_list "TO_STORE" "[none]" $temp
+    else
+        select_list "TO_STORE" $temp
+    fi
+    eval ''$returnvar'='$TO_STORE''
+}
+
+function real_depends()
 {
 
   if spell_exiled $1 ; then 
@@ -252,9 +348,15 @@ function depends()
   private_common_depends "$1" "on" "required" "$2" "$3"
 
 }
-function optional_depends()
-{
 
+function real_optional_depends()
+{
+  local NOQUESTION=false
+
+  if [[ "$1" == "no_question" ]]; then
+        shift;
+        NOQUESTION=true
+  fi
   if spell_exiled $1 ; then 
     message "${SPELL_COLOR}$1${DEFAULT_COLOR} has been exiled!"
     return 1
@@ -267,15 +369,20 @@ function optional_depends()
   #example: icewm:imlib:off:optional:--with-imlib:--with-xpm
   explode "`search_depends_status "$SPELL" "$1"`" ":" "status"
   if [[ $RECONFIGURE ]] || ! [[ ${status[2]} ]] ; then
-debug "DB" "status: ${status[*]}"
-    message "${SPELL_COLOR}$1${DEFAULT_COLOR} is an optional dependency for ${SPELL_COLOR}$SPELL${DEFAULT_COLOR} ($4)"
-    if spell_installed $1 || spell_held $1 ; then
-      query "Do you want to use ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "y" && 
-        install="on"
-    else
-      query "Do you want to cast ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "n" && 
-        install="on"
-    fi
+
+  if [[ $NOQUESTION == false ]]; then
+        message "${SPELL_COLOR}$1${DEFAULT_COLOR} is an optional dependency for ${SPELL_COLOR}$SPELL${DEFAULT_COLOR} ($4)"
+       if spell_installed $1 || spell_held $1 ; then
+          query "Do you want to use ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "y" && 
+            install="on"
+        else
+          query "Do you want to cast ${SPELL_COLOR}$1${DEFAULT_COLOR}?" "n" && 
+            install="on"
+        fi
+  else
+    install="on"
+  fi
+
   elif [[ ${status[2]} == on ]] ; then
     install="on"
   fi
@@ -291,7 +398,7 @@ debug "DB" "status: ${status[*]}"
 ## C<requires email-client> returns true if evolution is installed.
 ##
 #---------------------------------------------------------------------
-requires()  { 
+real_requires()  { #deprecated, martin 20030906 
 
   local CANDIDATES SATISFIED CANDIDATE 
   local temp found
@@ -339,11 +446,9 @@ requires()  {
 
 function private_common_depends()
 {
-debug "DB" "private_common_depends - $*"
   add_depends "$SPELL" "$@"
   
   if [[ $2 == on ]] && private_should_cast $1 ; then
-debug "DB" "adding a new depends here."
     NEW_DEPENDS=( "${NEW_DEPENDS[@]}" $1 )
   fi
   
@@ -395,7 +500,6 @@ function private_add_depends()
   done
   SPELLS=( "${SPELLS[@]}" ${NEW_DEPENDS[*]} )
 
-  debug "DB" "adding ${NEW_DEPENDS[*]}"
 
 }
 
