------------------------------------------------------------ revno: 26 committer: David Brown <dmlb2000@dmlb2004> branch nick: stage-root timestamp: Sun 2006-04-23 21:22:09 -0700 message:   merged from devel sorcery     ------------------------------------------------------------     merged: astitt@sourcemage.org-20060424014818-3d7be36d78d14708     committer: Andrew Stitt <astitt@sourcemage.org>     branch nick: devel-hack4     timestamp: Sun 2006-04-23 18:48:18 -0700     message:       fix bug 8070, make changelog viewing timeout     ------------------------------------------------------------     merged: astitt@sourcemage.org-20060424004600-7410dcc139b66a71     committer: Andrew Stitt <astitt@sourcemage.org>     branch nick: devel-hack4     timestamp: Sun 2006-04-23 17:46:00 -0700     message:       fix bug 9415, add some sanity checking to summon     ------------------------------------------------------------     merged: astitt@sourcemage.org-20060424001110-98d1bde767df28d7     committer: Andrew Stitt <astitt@sourcemage.org>     branch nick: devel-hack4     timestamp: Sun 2006-04-23 17:11:10 -0700     message:       svn should be non-interactive     ------------------------------------------------------------     merged: astitt@sourcemage.org-20060421153115-bb5ea4d0fd2f72f4     committer: Andrew Stitt <astitt@sourcemage.org>     branch nick: devel     timestamp: Fri 2006-04-21 08:31:15 -0700     message:       fix bug 11372, and some other summon issues

diff --git a/var/lib/sorcery/modules/libsorcery b/var/lib/sorcery/modules/libsorcery
--- a/var/lib/sorcery/modules/libsorcery
+++ b/var/lib/sorcery/modules/libsorcery
@@ -960,7 +960,6 @@ function sorcery_history() {
 ##
 #---------------------------------------------------------------------
 function get_new_changes() {
-    local PAGER2="$(override_pager)"
     local msg="$1"
     local date="$2"
     # This needs some explaination:
@@ -990,7 +989,9 @@ function get_new_changes() {
         echo "$msg"
         echo
         echo "$changelog"
-      } | $PAGER2
+      }  > $TMP_DIR/pagerdata
+      timeout_pager "$TMP_DIR/pagerdata"
+      rm $TMP_DIR/pagerdata
     else
       echo "$msg"
       echo
@@ -998,9 +999,26 @@ function get_new_changes() {
     fi
 }
 
-function override_pager() {
-  #placeholder for a proper fix for http://bugs.sourcemage.org/show_bug.cgi?id=8070
-  if [ "$PAGER" == "less" ]; then echo "more"; else echo "$PAGER"; fi
+
+#---------------------------------------------------------------------
+## Pager with timeouts, cannot be used from a pipe.
+## Invokes a subshell in case there are other background jobs running
+#---------------------------------------------------------------------
+function timeout_pager() { (
+  $PAGER "$@" &
+  sleep 1
+  for ((i=0;i<PAGER_TIMEOUT*10;i++)) ; do
+    jobs &>/dev/null # this makes bash clean up so the next line works
+    [[ "$(jobs)" ]] || return 0
+    sleep .1
+  done
+  jobs -p|xargs kill
+  jobs &>/dev/null # hide the [Done [2] blah blah] message
+  stty sane
+  if query "\nPager timeout, continue viewing $@" n; then
+    $PAGER "$@"
+  fi
+) 2>/dev/null # hides less complaining that it was killed
 }
 
 #---------------------------------------------------------------------
