proj/proj3/ => devel This is all the new downloading stuff. Assuming all is well no one should notice anything different :-)
Several files have empty changes, p4 thinks there are
un-integrated changes, or identical changes, not sure how that
happened.

diff --git a/var/lib/sorcery/modules/libsummon b/var/lib/sorcery/modules/libsummon
--- a/var/lib/sorcery/modules/libsummon
+++ b/var/lib/sorcery/modules/libsummon
@@ -8,6 +8,7 @@
 ## and to make it so cast doesn't have to actually run the summon script.
 ##
 ## @Copyright Copyright (C) 2004 The Source Mage Team <http://www.sourcemage.org>
+## @Copyright Copyright (C) 2005 The Source Mage Team <http://www.sourcemage.org>
 ##
 ## @Contributors Andrew Stitt <astitt@sourcemage.org)
 ## @Contributors Paul Mahon <pmahon@sourcemage.org)
@@ -26,71 +27,378 @@
 ##
 #---------------------------------------------------------------------
 function summon_spell() {
+  $STD_DEBUG
   local SPELL=$1
+  local rc=1
+  # FIXME trylock might fail
   if [ -n "${SPELL}" ] && trylock_resources "summon" "${SPELL}"; then
+    #local dl_dir=/tmp/sorcery/summon/${SPELL:-none}
+    local dl_dir=$TMP_DIR/${SPELL:-none}
+    debug "libsummon" "dl_dir is $dl_dir"
+    mkdir -p $dl_dir && pushd $dl_dir &>/dev/null &&
+
     # run in a subshell rather than try to unset_details
     # and instead jump through hoops to get the return code correctly
-    ( run_details    &&
-      get_spell_files_and_urls | download_files && rc=0
+    ( local rc=1
+      run_details    &&
+      persistent_load &&
+      if test -x $SCRIPT_DIRECTORY/DOWNLOAD ; then
+        . $SCRIPT_DIRECTORY/DOWNLOAD
+      else
+        default_download
+      fi &&
+      persistent_save
       # save the rc, then unlock
+      rc=$?
       unlock_resources "summon" "${SPELL}"
-      if [ ${rc:-1}==0 ]; then
+
+      if [[ $rc == 0 ]]; then
         activity_log "summon" "$SPELL"  "$VERSION" "success"
       else
         activity_log "summon" "$SPELL"  "$VERSION" "failure"
       fi
+
       # this actually only returns from the subshell, not the function
-      return ${rc}
-    ) && return 0
+      return $rc
+    ) &&
+    popd &>/dev/null
+    rm -rf $dl_dir
+    rc=$?
   fi
-  return 1
+  return $rc
 }
 
-#---------------------------------------------------------------------
-## @param A list of spells
-## Will call summon_spell for each spell found in "$*"
+#-------------------------------------------------------------------------
+## Helper routine to dump out the files and urls for a spell given that
+## the caller has run run_details.
 ##
-#---------------------------------------------------------------------
-function summon_spells() {
-  local SPELLS="$*"
-  local SPELL
-  [ -z "$SPELLS" ] && return 1
-  for  SPELL  in  $SPELLS;  do
-    summon_spell $SPELL
+## @Stdout multiple lines, one per SOURCE/SOURCEx as "SOURCE SOURCE_URL[0] SOURCE_URL[1]"
+#-------------------------------------------------------------------------
+function get_spell_files_and_urls() {
+  $STD_DEBUG
+  local url src
+  for src in $(real_get_source_nums SOURCE); do
+    url="$src"'_URL[*]'
+    src="${!src}"
+    [[ ${src} ]] && echo ${src} ${!url}
   done
 }
 
-#---------------------------------------------------------------------
-## @param A list of spells
-## @global PRINT_TYPE
-## This is mainly for summon, but might be useful for gaze as its
-## an information query function.
-#---------------------------------------------------------------------
-function summon_print_spells() {
-  local SPELLS="$*"
-  [ -z "$SPELLS" ] && return 1
 
-  for  SPELL  in  $SPELLS;  do
-    # run in a subshell rather than try to unset_details
-    # its a fork either way, and this way leaves us less open for surprises
-    ( run_details  &&
-      get_spell_files_and_urls|while read -a dl_array; do
-        if [ "$PRINT_TYPE" == source ]; then
-          echo "${dl_array[0]}"
-        elif [ "$PRINT_TYPE" == one_url ]; then
-          [ -n "${dl_array[1]}" ] && echo "${dl_array[1]}"
-        elif [ "$PRINT_TYPE" == all_urls ]; then
-          unset dl_array[0]
-          [ -n "${dl_array[*]}" ] && echo "${dl_array[*]}"
-        elif [ "$PRINT_TYPE" == raw ]; then
-          echo "${dl_array[*]}"
-        else
-          echo "unknown value of PRINT_TYPE $PRINT_TYPE we shouldn't get here"
-          echo "please file a bug if you see this, thanks."
-          exit 1
-        fi
-      done
-    )
+#-------------------------------------------------------------------------
+## @param none
+## 
+## Call acquire_src for each SOURCEx_URL
+##
+#-------------------------------------------------------------------------
+function real_default_download() {
+  $STD_DEBUG
+  local SOURCE_NUMBER
+  for SOURCE_NUMBER in $(real_get_source_nums X); do
+    SOURCE_NUMBER=${SOURCE_NUMBER/X/}
+    acquire_src $SOURCE_NUMBER
   done
 }
 
+
+#-------------------------------------------------------------------------
+## @param source number or '' for the first $SOURCE
+##
+## Acquire the source. Check locally unless options insist on not
+## doing so.
+##
+## Inspects $FORCE_DOWNLOAD and ${FORCE_DOWNLOAD[$srcnum]}
+## if either are set then downloading is forced, a local copy of the
+## file is ignored.
+#-------------------------------------------------------------------------
+function real_acquire_src() {
+  $STD_DEBUG
+  local DLNUM="$1"
+  local SVAR="SOURCE${DLNUM}"
+  local target=${!SVAR}
+
+  
+  REASON="for spell ${SPELL_COLOR}${SPELL}${DEFAULT_COLOR}"
+
+  # maybe we already have the file
+  # but we can only use it if not FORCE_DOWNLOADing
+  if file_exists "$SOURCE_CACHE/$target " &&
+     ! [[ ${FORCE_DOWNLOAD} ]] &&
+     ! [[ ${FORCE_DOWNLOAD[${DLNUM:-1}]} ]] ; then
+    message  "${MESSAGE_COLOR}Found source file"             \
+             "${FILE_COLOR}${target}${DEFAULT_COLOR}"     \
+             "$REASON in ${FILE_COLOR}${SOURCE_CACHE}${DEFAULT_COLOR}"
+    return 0
+  fi
+  # else the source must be downloaded/updated
+  download_src "$DLNUM"
+}
+
+#-------------------------------------------------------------------------
+## @param source number or '' for the first $SOURCE
+## 
+## Expands $SOURCEx, $SOURCEx_URL[*] and $SOURCEx_HINTS
+## then calls download_src_args with them.
+##
+#-------------------------------------------------------------------------
+function real_download_src() {
+  $STD_DEBUG
+  local DLNUM="$1"
+  local SVAR="SOURCE${DLNUM}"
+  local SURLVAR=${SVAR}'_URL[*]'
+  local SHINTVAR=${SVAR}'_HINTS'
+
+  local target=${!SVAR}
+  local urls=${!SURLVAR}
+  local hints=${!SHINTVAR}
+
+  [[ "$target" ]] || {
+    message "Empty value in $SVAR!!"
+    return 1
+  }
+  [[ "$urls" ]] || {
+    message "No urls in $SURLVAR!!"
+    return 1
+  }
+  download_src_args "$target" "$urls" "$hints"
+}
+
+#-------------------------------------------------------------------------
+## @param file
+## @param url list
+## @param url options
+##
+## Download the resource, handles file and tree discrepencies, if a tree is
+## downloaded it is repackaged as the specified file for later use.
+##
+## Only tar.bz2 files are acceptable caches for repackaged trees
+##
+#-------------------------------------------------------------------------
+function download_src_args() {
+  $STD_DEBUG
+  local target="$1"
+  local urls="$2"
+  local hints="$3"
+
+  message  "${MESSAGE_COLOR}Downloading source file"       \
+           "${FILE_COLOR}${target}${DEFAULT_COLOR}"     \
+           "${REASON}"
+
+  # get the update tree if we think there is one
+  local new_target=$target
+  unpack_for_update "$target" "$urls" "$hints" new_target guess_type
+
+  # this does the actual downloading:
+  local summon_type summon_target
+  if ! download_src_sub "$new_target" "$urls" "$hints" \
+                                       summon_target summon_type; then
+    message  "${PROBLEM_COLOR}Download of"            \
+             "${FILE_COLOR}${target}${DEFAULT_COLOR}"   \
+             "${PROBLEM_COLOR}failed${DEFAULT_COLOR}"
+    return 1
+  fi
+
+  # look at what we got
+  if ! [[ $summon_target ]] ; then
+    message "${PROBLEM_COLOR}Empty value for downloaded target, file a bug" \
+            "if you see this.${DEFAULT_COLOR}"
+    return 255
+  fi
+
+  # repackage if necessary and move to $SOURCE_CACHE
+  if [[ "$summon_type" == tree ]] ; then
+
+    # incorrect guess, set new_target appropriatly
+    if [[ "$guess_type" == file ]] ; then
+      new_target="${target/.tar.bz2/}"
+    fi
+
+    if ! test -d $summon_target; then
+      message "${PROBLEM_COLOR}Value for downloaded target ($summon_target)" \
+              "is not a directory, but a tree was downloaded, file a bug" \
+              "if you see this.${DEFAULT_COLOR}"
+      return 255
+    fi
+    if [[ $summon_target != $new_target ]] ; then
+      mv -f $summon_target $new_target
+    fi &&
+    message "Repackaging $target"
+    tar --remove-files -cjf $target $new_target &&
+    rm -rf $new_target
+  elif [[ "$summon_type" == file ]] ; then
+    # there is no penalty for guessing tree when the result is a file
+
+    if [[ $summon_target != $target ]] ; then
+      mv -f $summon_target $target
+    fi
+  else
+    message "${PROBLEM_COLOR}Unknown download type: \"$summon_type\""\
+            "at \"$summon_target\". Please file a bug if you see this." \
+            "${DEFAULT_COLOR}"
+    return 1
+  fi
+  rm -rf $SOURCE_CACHE/$target &&
+  mv $target $SOURCE_CACHE
+}
+
+#-------------------------------------------------------------------------
+##
+## @param file
+## @param url list
+## @param url options
+## @param summon target return value, pass by reference
+## @param summon type return value, pass by reference
+##
+## Download the resource, first try a leapforward url, then the given
+## urls and finally the fallbacks.
+#-------------------------------------------------------------------------
+function download_src_sub()  {
+
+  $STD_DEBUG
+
+  local target="$1"
+  local url_list="$2"
+  local hints="$3"
+  local _summon_target=$4
+  local _summon_type=$5
+
+  download_from_leapforward "$target" "$url_list" "$hints" \
+                            "$_summon_target" "$_summon_type" ||
+
+  url_download_expand_sort "$target" "$url_list" "$hints" \
+                           "$_summon_target" "$_summon_type" ||
+
+  download_from_fallback "$target" "$url_list" "$hints" \
+                         "$_summon_target" "$_summon_type"
+
+}
+
+#-------------------------------------------------------------------------
+##
+## Download the specified resource from the leapforward url if one is
+## given.
+##
+## @param file
+## @param url list
+## @param url options
+## @param summon target return value, pass by reference
+## @param summon type return value, pass by reference
+#-------------------------------------------------------------------------
+function download_from_leapforward() {
+  $STD_DEBUG
+  if ! [ -n "$LEAPFORWARD_URL" ]; then
+    return 1
+  fi
+
+  local target="$1"
+  local url_list="$2"
+  local hints="$3"
+  local _summon_target=$4
+  local _summon_type=$5
+  
+  message "${MESSAGE_COLOR}Attempting to get file from" \
+          "leap-forward mirror ${DEFAULT_COLOR}${LEAPFORWARD_URL}"
+  # leap forwards dont need to be expanded or sorted
+  url_download "$target" "$LEAPFORWARD_URL/$target" "$hints" \
+                                  "$_summon_target" "$_summon_type"
+}
+
+#-------------------------------------------------------------------------
+##
+## Attempt to get the resource from the fallback urls, try each one in
+## a random order.
+##
+## @param file
+## @param url list
+## @param url options
+## @param summon target return value, pass by reference
+## @param summon type return value, pass by reference
+##
+#-------------------------------------------------------------------------
+function download_from_fallback() {
+  $STD_DEBUG
+  local target="$1"
+  local url_list="$2"
+  local hints="$3"
+  local _summon_target=$4
+  local _summon_type=$5
+
+  message "${MESSAGE_COLOR}Attempting to get file from fall-back mirrors" \
+          "${DEFAULT_COLOR}"
+
+  # slow and painful buildup of all fallback mirrors in quasi random order
+  local i idx
+  local FALL_BACKS
+  local offset=$[${RANDOM} % $FURLNUM]
+  for (( i=0; $i < $FURLNUM; i++ ));  do
+    idx=$[($i + $offset) % $FURLNUM]
+    FALL_BACKS="$FALL_BACKS ${FALLBACK_URL_MIRROR[$idx]}/$target"
+  done
+  [ -n "$FALL_BACKS" ] && 
+  # dont order fall backs, above we use a random ordering
+  url_download "$target" "$FALL_BACKS" "$hints" "$_summon_target" \
+                                                "$_summon_type"
+}
+
+#-------------------------------------------------------------------------
+##
+## Make a guess as to whether or not the resource being downloaded
+## will be a file or a tree if it is a tree and the cached source exists
+## then unpack it in the current directory so it may be updated
+##
+## @param target
+## @param url_list
+## @param hints
+## @param new target return value pass by reference
+## @param guessed type return value pass by reference
+##
+##
+#-------------------------------------------------------------------------
+function unpack_for_update() {
+  $STD_DEBUG
+  local target="$1"
+  local url_list="$2"
+  local hints="$3"
+  local new_target_ref=$4
+  local guess_type_ref=$5
+  local _new_target
+  local _guess_type
+
+  # hard-coded list of url prefixes that generally download trees
+  local tree_prefixes="cvs dir rsync smgl_tla svn"
+  local prefix=$(url_get_prefix $url_list)
+  if ! list_find "$hints" file &&
+     list_find "$hints" tree || list_find "$tree_prefixes" "$prefix" ; then
+    _new_target="${target/.tar.bz2/}"
+    eval "$guess_type_ref=\"tree\""
+    eval "$new_target_ref=\"\$_new_target\""
+
+    # if $target exists in $SOURCE_CACHE and we think the download might be
+    # a tree, unpack it so the tree can be updated
+    if test -f $SOURCE_CACHE/$target && ! list_find "$hints" no_update; then
+      unpack_file_simple $target || return 1
+      if ! test -d "$_new_target" ; then
+        debug "libsummon" "unpacked $target but to somewhere strange"
+      fi
+    fi
+  else
+    eval "$new_target_ref=\"\$target\""
+    eval "$guess_type_ref=\"file\""
+  fi
+  return 0
+}
+#---------------------------------------------------------------------
+## This software is free software; you can redistribute it and/or modify
+## it under the terms of the GNU General Public License as published by
+## the Free Software Foundation; either version 2 of the License, or
+## (at your option) any later version.
+##
+## This software is distributed in the hope that it will be useful,
+## but WITHOUT ANY WARRANTY; without even the implied warranty of
+## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+## GNU General Public License for more details.
+##
+## You should have received a copy of the GNU General Public License
+## along with this software; if not, write to the Free Software
+## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
+#---------------------------------------------------------------------
diff --git a/var/lib/sorcery/modules/liburl b/var/lib/sorcery/modules/liburl
--- a/var/lib/sorcery/modules/liburl
+++ b/var/lib/sorcery/modules/liburl
@@ -5,8 +5,12 @@
 ##
 ##
 ## This file contains functions for downloading and verifying urls.
-## It does this by fowarding url download and verification requests to
-## the appropriate url handler.  For example, the request to download
+## It does this by extracting information from a url with url handlers
+## specific to that url type. The url handler also determines a download
+## handler to actually download the url.
+##
+## FIXME
+## For example, the request to download
 ## the following url is made through the generic F<url_download>
 ## function:
 ##
@@ -47,16 +51,17 @@
 ##
 ## <p>Implement Url Handlers</p>
 ##
-## The next (and final) step is to write the actual functions that
+## The next step is to write the actual functions that
 ## will handle url requests and put them in the new file you just
 ## created.  The functions that must be implemented are:
 ##
-##    url_<URL_PREFIX>_download <url>
-##    url_<URL_PREFIX>_verify <url>
-##    url_<URL_PREFIX>_set_options <option>
-##    url_<URL_PREFIX>_help
+##    url_<URL_PREFIX>_bucketize <url>
+##    url_<URL_PREFIX>_crack <url>
+##    url_<URL_PREFIX>_expand <url>
 ##    url_<URL_PREFIX>_hostname <url>
+##    url_<URL_PREFIX>_is_valid <url>
 ##    url_<URL_PREFIX>_netselect <url>
+##    url_<URL_PREFIX>_verify <url>
 ##
 ## The easiest way to figure out what to do is to look at
 ## one of the existing files (e.g., url_http handles http requests).
@@ -87,114 +92,173 @@ if ! [[ $URL_HANDLER_FILES ]] ; then
   done
 fi
 
-
 #---------------------------------------------------------------------
-## url_name_is_function <function name>
-## @param function name
-## @Type Private
-## @return 0 if argument is a valid function
-## @return 1 otherwise
-## Returns true if input argument is the name of an
-## existing function, false otherwise.
+## @param see url_download
+##
+## This is simply a wrapper around url_download which provides the
+## additional functionality of expanding and ranking urls.
+## Processes like summon should use this, more defined processes
+## like scribe and sorcery update will probably directly call url_download.
 ##
 #---------------------------------------------------------------------
-function url_is_function()  {
-  local  FUNCTION_NAME=$1
-  [  "`type -t $FUNCTION_NAME`"  =  "function"  ]
-}
+function url_download_expand_sort() {
+  $STD_DEBUG
+  local target=$1
+  local url_list=$2
+  local hints=$3
+  local udl_target=$4
+  local udl_type=$5
 
+  local url expanded_urls sorted_urls
 
-#---------------------------------------------------------------------
-## @Type Private
-## @param url 
-## @Stdout url prefix
-## @return 0 valid url
-## @return 1 otherwise
-## Takes a url and echos the url prefix.  Returns
-## true if a valid url could be found, returns false otherwise.
-##
-## This is the only place parsing of a url should take place outside of
-## a url_handler. Doing so elsewhere is bugworthy.
-##
-#---------------------------------------------------------------------
-function url_get_prefix()  {
-  local URL=$1
-  local  URL_PREFIX=`echo $URL | sed "s/[\:\/\/].*$//"` 
-  [  -n  "$URL_PREFIX"  ]  &&
-  echo    $URL_PREFIX
-}
+  debug "liburl" "$FUNCNAME -- $@"
+  # you can't expect me to download something without urls...
+  [ -z "$urls" ] && return 255
 
-#---------------------------------------------------------------------
-## @Type Private
-## @param url 
-## @Stdout url hostname
-## @return 0 valid url
-## @return 1 otherwise
-## Takes a url and echos the url hostname. Returns
-## true if a hostname could be found, returns false otherwise.
-##
-#---------------------------------------------------------------------
-function url_get_hostname()  {
-  local tmp_url=$1 tmp_prefix
-  tmp_prefix=$(url_get_prefix $tmp_url)                 &&
-  url_is_function url_${tmp_prefix}_hostname            &&
-  url_${tmp_prefix}_hostname $tmp_url
-}
-
-#---------------------------------------------------------------------
-## @Type Private
-## @param url 
-## @Stdout url netslect output
-## @return 0 valid url
-## @return 1 otherwise
-## Prints the netselect output from the url handlers attempt at
-## running netselect.
-##
-#---------------------------------------------------------------------
-function url_get_netselect()  {
-  local tmp_url=$1 tmp_prefix
-  tmp_prefix=$(url_get_prefix $tmp_url)                 &&
-  url_is_function url_${tmp_prefix}_hostname            &&
-  url_${tmp_prefix}_netselect $tmp_url
-}
-
-
-#---------------------------------------------------------------------
-## @Type Private 
-## @Global BASE_URL FILE
-## If BASE_URL is set, then change URL to 
-## use BASE_URL as the download location.  Also sets FILE variable.
-#---------------------------------------------------------------------
-function url_change_base()  {
-  if  [  -n  "$BASE_URL"  ]  &&  [  -n  "$FILE"  ];  then  
-    URL="$BASE_URL/`basename $FILE`"
+  # expand urls
+  url_expand_urls expanded_urls "$urls"
+  if ! [[ "$expanded_urls" ]] ; then
+    message "No expanded urls! If you get this it is a sorcery bug"
+    return 1
   fi
+  debug "liburl" "expanded urls $expanded_urls"
+  # sort urls 
+  url_sort_urls sorted_urls "$expanded_urls"
+  if ! [[ "$sorted_urls" ]] ; then
+    message "No sorted urls! If you get this it is a sorcery bug"
+    return 1
+  fi
+  debug "liburl" "sorted urls $sorted_urls"
+  url_download "$1" "$sorted_urls" "$3" "$4" "$5"
 }
 
-
 #---------------------------------------------------------------------
-## @param url
-## @return 0 valid url
+## @param target	Expected target file or tree, this is only a
+##                      suggestion, and the download handler may ignore it.
+## @param url_list	List of urls to get the target from
+## @param hints		Hints, these help the function determine what
+##			type of thing it is downloading or other tunables.
+## @param udl_target	Name of variable in which to store the name of the
+##			result directory or file
+## @param udl_type	Name of the variable in which to store the type of
+##			thing downloaded
+##
+## @return 0 if file could be downloaded
 ## @return 1 otherwise
-## Returns true if the given url is a valid url understood by the url
-## library, returns false otherwise.
+## Downloads the specified url.  Returns true if file could be 
+## downloaded, false otherwise.
+##
 ##
 #---------------------------------------------------------------------
-function url_is_valid()  {
-  [ "$1" == " " ] && return 1 #If it's only a space, it's not valid
-  local  URL_PREFIX=`echo $1 | sed "s/[\:\/\/].*$//"` 
-  [  -n  "$URL_PREFIX"  ]  &&
-  url_is_function "url_${URL_PREFIX}_download"
+function url_download() {
+  $STD_DEBUG
+  local target=$1
+  local url_list=$2
+  local hints=$3
+  local udl_target=$4
+  local udl_type=$5
+
+  local url
+
+  debug "liburl" "$FUNCNAME -- $@"
+
+  # you can't expect me to download something without urls...
+  [ -z "$url_list" ] && return 255
+
+  # sanity check urls
+  local valid_urls
+  url_get_valid_urls valid_urls "$url_list"
+  if ! [[ "$valid_urls" ]] ; then
+    message "No valid urls!"
+    return 1
+  fi
+
+  hash_reset dl_buckets
+  local bucket
+  # bucketize
+  for url in $valid_urls; do
+    bucket=$(url_bucketize "$url")
+    if [[ $bucket ]] ; then
+      hash_append dl_buckets "$bucket" "$url"
+    else
+      message "Failed to find a download handler for $url, this is likely to be a sorcery bug"
+    fi
+  done
+  
+  # sort buckets, someday a better algorithm may be used, however
+  # this should be sufficient for now.
+  buckets=$(hash_get_table_fields dl_buckets|sort)
+
+  # iterate through buckets
+  for bucket in $buckets; do
+    dl_get_bucket "$bucket" "$target" "$(hash_get dl_buckets $bucket)" \
+                  "$hints" "$udl_target" "$udl_type"
+    rc=$?
+    if [[ $rc == 0 ]] ; then
+      debug "liburl" "url_download -- downloaded $url $udl_r_target $udl_r_type"
+      return 0
+    fi
+  done
+  return 1
 }
 
+
+#---------------------------------------------------------------------
+## @param urllist
+#---------------------------------------------------------------------
+function url_get_valid_urls() {
+  $STD_DEBUG
+  local upvar="$1"
+  local url_list="$2"
+  for url in $url_list; do
+    if url_is_valid "$url"; then
+      list_add $upvar "$url"
+    else
+      message "Invalid url: $url"
+    fi
+  done
+}
+
+
+#---------------------------------------------------------------------
+## @param urllist
+##
+## Frontend to expand urls into a nice list.
+#---------------------------------------------------------------------
+function url_expand_urls() {
+  $STD_DEBUG
+  local upvar="$1"
+  local url_list="$2"
+  for url in $url_list; do
+    # this should expand to something or return itself
+    list_add "$upvar" $(url_expand "$url")
+  done
+}
+
+#---------------------------------------------------------------------
+## @param urllist
+#---------------------------------------------------------------------
+function url_sort_urls() {
+  $STD_DEBUG
+  local upvar="$1"
+  local url_list="$2"
+  if [[ $NET_SELECT == on ]]  &&  spell_installed "netselect" ;  then
+    lock_resources "network" "network"
+    message -n "${CHECK_COLOR}Looking for the fastest mirror site...${DEFAULT_COLOR} "
+    dl_connect
+    url_list=$(url_rank $url_list 2> /dev/null)
+    dl_disconnect
+    unlock_resources "network" "network"
+    message " done."
+  fi
+  eval "$upvar=\$url_list"
+}
 
 #---------------------------------------------------------------------
 ## @param urllist
 ## @Stdout new list
 ## Ranks the urls in order of speed from fastest to slowest using netselect
 ## Makes use of url_<url_type>_hostname functions.
-##
-## T
 ##
 ## If multiple urls from the same hostname are passed in, their ordering
 ## is preserved, although that group of urls may move as a whole in
@@ -222,7 +286,6 @@ function url_rank() {
   function url_rank_divide_by_prefix() {
     local tmp_url=$1 tmp_prefix
     tmp_prefix=$(url_get_prefix $tmp_url)                 &&
-    url_is_function url_${tmp_prefix}_hostname            &&
     hash_append url_div_hash $tmp_prefix $tmp_url
   }
   iterate url_rank_divide_by_prefix " $IFS" $urlList
@@ -236,12 +299,12 @@ function url_rank() {
     # into the following bash code, which is then executed
     # url_speed[69]="${url_speed[69]} url1"
     # url_speed[234]="${url_speed[234]} url2"
-    eval $(url_${tmp_prefix}_netselect $tmp_list|
+    eval $(url_netselect $tmp_list|
       awk '{printf "url_speed[%s]=\"${url_speed[%s]} %s\";",$1,$1,$2}')
   done
   
   # since we put things in url_speed indexed by speed, the * should
-  #expand back in sorted order
+  # expand back in sorted order
 
   sortedList=$(echo ${url_speed[*]})
   debug "liburl" "Ordered list pre-sanity check is $sortedList"
@@ -269,94 +332,156 @@ function url_rank() {
   fi
 }
 
-
-
 #---------------------------------------------------------------------
-## @param url
-## @return 0 if file could be downloaded
+## @Type Private
+## @param url 
+## @Stdout url prefix
+## @return 0 valid url
 ## @return 1 otherwise
-## @Global FILE
-## Downloads the specified url.  Returns true if file could be 
-## downloaded, false otherwise.  The name of the downloaded file
-## is left in the FILE variable.
+## Takes a url and echos the url prefix.  Returns
+## true if a valid url could be found, returns false otherwise.
+##
+## This is the only place parsing of a url should take place outside of
+## a url_handler. Doing so elsewhere is bugworthy.
 ##
 #---------------------------------------------------------------------
-function url_download() {
-  local URL_LIST=$*
-  local SUCCESS=false
-
-  debug "liburl" "url_download() $*"
-
-  # you can't expect me to download something without urls...
-  [ -z "$URL_LIST" ] && return 1
-  
-  if (  [[ $NET_SELECT == on ]]  &&  spell_installed "netselect"  );  then
-    lock_resources "network" "network"
-    message -n "${CHECK_COLOR}Looking for the fastest mirror site...${DEFAULT_COLOR} "
-    URL_LIST=`url_rank $URL_LIST 2> /dev/null` 
-    unlock_resources "network" "network"
-    message " done."
-  fi
-
-  for URL in $URL_LIST; do
-    if  url_is_valid $URL                             &&
-        url_change_base                               &&
-        URL_PREFIX=`url_get_prefix $URL`              &&
-        url_is_function "url_${URL_PREFIX}_download"  && 
-        url_${URL_PREFIX}_download $URL;              then
-        SUCCESS=true
-        break;
-    fi
-  done
-
-
-  $SUCCESS
-}
-
-
-#---------------------------------------------------------------------
-## @param url
-## @return 0 url could be verified
-## @return 1 otherwise
-## Verifies the specified url.  Returns true if file could be 
-## verified, false otherwise.
-##
-#---------------------------------------------------------------------
-function url_verify() {
+function url_get_prefix()  {
+  $STD_DEBUG
   local URL=$1
-  
-  url_change_base
-  URL_PREFIX=`url_get_prefix $URL`            &&
-  url_is_function "url_${URL_PREFIX}_verify"  && 
-  url_${URL_PREFIX}_verify $URL
+  local  URL_PREFIX=`echo $URL | sed "s/[\:\/\/].*$//"` 
+  [  -n  "$URL_PREFIX"  ]  &&
+  echo    $URL_PREFIX
 }
 
 
 #---------------------------------------------------------------------
-## @param option 
-## Set options for url handling
+## @Type Private
+## @param url 
+## @param url prefix
+## @stdout url sans prefix
+#---------------------------------------------------------------------
+function url_strip_prefix() {
+  $STD_DEBUG
+  echo $1 | sed "s!^$2://!!"
+}
+
+#---------------------------------------------------------------------
+## url handler api functions. Use these to access a url specific
+## functionality/data.
+#---------------------------------------------------------------------
+
+#---------------------------------------------------------------------
+## @param url 
+## @stdout dl handler
+##
+## Get the download handler for this url
+#---------------------------------------------------------------------
+function url_bucketize()  {
+  $STD_DEBUG
+  url_generic_apifunc bucketize $1
+}
+
+#---------------------------------------------------------------------
+## @param url 
+##
+## Parse the url somehow. The results are url specific right now,
+## this is usually only called by dl handlers who know what url types
+## they can handle, and thus, understand the return value.
+#---------------------------------------------------------------------
+function url_crack()  {
+  $STD_DEBUG
+  url_generic_apifunc crack $1
+}
+
+#---------------------------------------------------------------------
+## @param url(s)
+## @stdout urls
+##
+## Attempt to get more similar urls to the given one based on the
+## sorcery mirrors files. Most url types simply expand to the input.
+#---------------------------------------------------------------------
+function url_expand()  {
+  $STD_DEBUG
+  url_generic_apifunc expand "$@"
+}
+
+#---------------------------------------------------------------------
+## @param url 
+##
+## Verify the url, this usually means going out to the internet and
+## somehow determining if the link is good.
+#---------------------------------------------------------------------
+function url_verify()  {
+  $STD_DEBUG
+  url_generic_apifunc verify $1
+}
+
+#---------------------------------------------------------------------
+## @param url 
+## @Stdout url hostname
+## @return 0 valid url
+## @return 1 otherwise
+## Takes a url and echos the url hostname. Returns
+## true if a hostname could be found, returns false otherwise.
 ##
 #---------------------------------------------------------------------
-function url_set_options() {
-  for URL_TYPE in ${URL_TYPES[@]}; do
-    url_is_function url_${URL_TYPE}_set_options &&
-    url_${URL_TYPE}_set_options $@
-  done
+function url_hostname()  {
+  $STD_DEBUG
+  url_generic_apifunc hostname $1
 }
 
-
 #---------------------------------------------------------------------
-## @Stdout help message 
-## Prints help message regarding url handling
+## @param url 
+## @Stdout url netslect output
+## @return 0 valid url
+## @return 1 otherwise
+## Prints the netselect output from the url handlers attempt at
+## running netselect.
 ##
 #---------------------------------------------------------------------
-function url_help() {
-  for URL_TYPE in ${URL_TYPES[@]}; do
-    url_is_function url_${URL_TYPE}_help &&
-    url_${URL_TYPE}_help
-  done
+function url_netselect()  {
+  $STD_DEBUG
+  url_generic_apifunc netselect "$@"
 }
 
+#---------------------------------------------------------------------
+## @param url
+## @return 0 valid url
+## @return 1 otherwise
+## Returns true if the given url is a valid url understood by the url
+## library, returns false otherwise.
+##
+#---------------------------------------------------------------------
+function url_is_valid()  {
+  $STD_DEBUG
+  url_generic_apifunc is_valid $1
+}
+
+
+#---------------------------------------------------------------------
+## @param function name
+## @param url(s)
+##
+## This implements the common code for simple url handler inheritence.
+## The above url api functions call this which then calls the handler
+## specific function, if it exists, or the default version. This
+## allows url handlers to only override functions as necessary.
+##
+## If multiple urls are given, the prefix is assumed of all of them
+## is assumed to be the same.
+##
+#---------------------------------------------------------------------
+function url_generic_apifunc() {
+  local tmp_func=$1
+  shift
+  local tmp_url=$1 tmp_prefix
+  tmp_prefix=$(url_get_prefix $1)
+  if misc_is_function url_${tmp_prefix}_${tmp_func}; then
+    url_${tmp_prefix}_${tmp_func} "$@"
+  else
+    url_default_${tmp_func} "$@"
+  fi
+}
 
 #---------------------------------------------------------------------
 ## This software is free software; you can redistribute it and/or modify
@@ -373,4 +498,3 @@ function url_help() {
 ## along with this software; if not, write to the Free Software
 ## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #---------------------------------------------------------------------
-
