1.14.0 release brute-sync from devel

diff --git a/var/lib/sorcery/modules/libtrack b/var/lib/sorcery/modules/libtrack
--- a/var/lib/sorcery/modules/libtrack
+++ b/var/lib/sorcery/modules/libtrack
@@ -6,6 +6,17 @@
 #---------------------------------------------------------------------
 
 #---------------------------------------------------------------------
+##
+##  Initialize libtrack, currently this is just the modified files list.
+##  This is used by cast to exclude files it's modified from the md5 list.
+##
+#---------------------------------------------------------------------
+function libtrack_init() {
+  [[ $__MODIFIED_FILES ]] || export __MODIFIED_FILES="$TMP_DIR/modified_files"
+}
+
+
+#---------------------------------------------------------------------
 ## @Stdin list of files
 ## @Stdout list of files
 ## Reads a list of files from standard in, and returns a list of the
@@ -26,7 +37,8 @@ function exists()  {
 ##
 #---------------------------------------------------------------------
 function real_track_manual()  {
-  if  [[  -z  "$INSTALLWATCHFILE"  ]];  then
+  if  [[ -z "$STAGED_INSTALL" || $STAGED_INSTALL == off ]] &&
+      [[ -z "$INSTALLWATCHFILE"  ]] ;  then
     echo "Can't tell installwatch to manually track... installwatch isn't running."
     return 1
   fi
@@ -37,6 +49,105 @@ function real_track_manual()  {
   return 0
 }
 
+#--------------------------------------------------------------------
+## Some simple castfs sanity checking
+## make a file, check to see if it exists, check to see if the
+## contents of the file is what we made it
+#--------------------------------------------------------------------
+function run_castfs_sanity()
+{
+  export CASTFS_LOGFILE=${CASTFS_DBGLOG}
+  export CASTFS_DBGLVL=${CASTFS_DEBUG_LEVEL}
+  debug  "libtrack" "$FUNCNAME on $SPELL"
+
+  # first check if /dev/null is really a character device #13315
+  if [[ ! -c /dev/null ]]; then
+    debug "libtrack" "$FUNCNAME failure: damaged /dev/null"
+    return 1
+  fi
+
+  mkdir -p "${TMP_DIR}/test-mount" &&
+  mkdir -p "${TMP_DIR}/test-stage" &&
+  castfs "${TMP_DIR}/test-mount" -o "stage=${TMP_DIR}/test-stage" -o "ignore=/tmp" &&
+  pushd "${TMP_DIR}/test-mount" > /dev/null &&
+  (
+    (echo stuff > foo) &&
+    (ls foo > /dev/null 2>&1) &&
+    (test "stuff" = "`cat foo`") &&
+    rm -f foo
+  )
+  local rc=$?
+  popd > /dev/null
+  if [[ $rc == 0 ]]
+  then
+    debug "libtrack" "$FUNCNAME success"
+  else
+    debug "libtrack" "$FUNCNAME failure"
+  fi
+  umount -l "${TMP_DIR}/test-mount"
+  return $rc
+}
+
+#---------------------------------------------------------------------
+##
+## Starts Translation Stage Root
+##
+#---------------------------------------------------------------------
+function real_invoke_stage_root()
+{
+  export CASTFS_LOGFILE=${CASTFS_DBGLOG}
+  export CASTFS_DBGLVL=${CASTFS_DEBUG_LEVEL}
+  local CASTFS_IGNORE_LIST=""
+  local LOCAL_IGNORE_DIRS="${CCACHE_DIR} ${DISTCC_DIR}"
+  # this forks and daemonizes so it will exit you simply unmount the dir to stop the process
+  for dir in ${CASTFS_UNSTAGED_PATHS} ${LOCAL_IGNORE_DIRS}
+  do
+    CASTFS_IGNORE_LIST="${CASTFS_IGNORE_LIST} -o ignore=$dir"
+  done &&
+  castfs "${STAGE_DIRECTORY}/MOUNT" -o "stage=${STAGE_DIRECTORY}/TRANSL" $CASTFS_IGNORE_LIST &&
+  for dir in /dev /dev/pts /proc /sys
+  do
+    mount -o bind "$dir" "${STAGE_DIRECTORY}/MOUNT$dir"
+  done
+}
+
+#---------------------------------------------------------------------
+##
+## Stops Translation Stage Root
+##
+#---------------------------------------------------------------------
+function real_devoke_stage_root()
+{
+  unset CASTFS_LOGFILE
+  unset CASTFS_DBGLVL
+  for dir in /dev/pts /dev /proc /sys
+  do
+    umount -l "${STAGE_DIRECTORY}/MOUNT$dir"
+  done &&
+  umount -l "${STAGE_DIRECTORY}/MOUNT"
+}
+
+#---------------------------------------------------------------------
+##
+## Prepare Stage Root
+##
+#---------------------------------------------------------------------
+function prepare_stage_root()
+{
+  mk_source_dir "${STAGE_DIRECTORY}" &&
+  mk_source_dir "${STAGE_DIRECTORY}/TRANSL" &&
+  mk_source_dir "${STAGE_DIRECTORY}/MOUNT"
+}
+
+#---------------------------------------------------------------------
+##
+## Destroy Stage Root
+##
+#---------------------------------------------------------------------
+function destroy_stage_root()
+{
+  rm_source_dir $STAGE_DIRECTORY
+}
 
 #---------------------------------------------------------------------
 ##
@@ -46,17 +157,9 @@ function real_track_manual()  {
 function real_invoke_installwatch()  {
   if  [  -e  /usr/lib/installwatch.so  ];  then
     export  INSTALLWATCHFILE=$IW_LOG
-    export  INSTW_LOGFILE=$IW_LOG
-    export  INSTW_DBGFILE="$TMP_DIR/dbgfile"
-    export  INSTW_ROOTPATH=$TMP_DIR
-    export  INSTW_TRANSL=0
-    export  INSTW_BACKUP=0
-    export  INSTW_DBGLVL=0
-    export  INSTW_EXCLUDE="/dev,/proc,/tmp,/var/tmp,/usr/src,/sys"
     export  LD_PRELOAD=/usr/lib/installwatch.so
   fi
 }
-
 
 #---------------------------------------------------------------------
 ##
@@ -66,15 +169,25 @@ function real_invoke_installwatch()  {
 function real_devoke_installwatch()  {
   unset  LD_PRELOAD
   unset  INSTALLWATCHFILE
-  unset  INSTW_LOGFILE
-  unset  INSTW_DBGFILE
-  unset  INSTW_ROOTPATH
-  unset  INSTW_TRANSL
-  unset  INSTW_BACKUP
-  unset  INSTW_DBGLVL
-  unset  INSTW_EXCLUDE	      
 }
 
+function is_castfs_installed()
+{
+  local loc
+  if smgl_which castfs loc >/dev/null 2>&1 &&
+     (
+       modprobe fuse > /dev/null 2>&1 ||
+       grep -q '^nodev[[:space:]]*fuse$' /proc/filesystems
+     ) &&
+     [[ -c /dev/fuse ]]
+  then
+    message "${MESSAGE_COLOR}staging enabled${DEFAULT_COLOR}"
+    return 0
+  else
+    message "${MESSAGE_COLOR}staging disabled${DEFAULT_COLOR}"
+    return 1
+  fi
+}
 
 #---------------------------------------------------------------------
 ##
@@ -87,7 +200,7 @@ function parse_iw()  {
   # it is EXTREMELY IMPORTANT that this variable contains an actual
   # tab character and not some number of spaces. Otherwise BAD THINGS
   # will happen.
-  local TAB="	"
+  local TAB=$'\t'
   OMIT_IN="${TAB}rename\|${TAB}symlink\|${TAB}unlink"
 
   grep -v "$OMIT_IN" $INPUT | cut -f3 | grep "^/" | sed 's#^//#/#g'
@@ -106,18 +219,50 @@ function create_install_log()  {
   local OUTPUT=$2
 
   rm -f $OUTPUT
-  parse_iw $INPUT                     |
-  sort                                |
-  uniq                                |
-  install_log_filter $INSTALL_ROOT "" |
-  grep -v -x ""                       |
-  filter_excluded                     |
-  install_log_filter "" $INSTALL_ROOT |
-  exists                              >  $OUTPUT
+  if [[ $STAGED_INSTALL != off ]]
+  then
+    find "${STAGE_DIRECTORY}/TRANSL/"   |
+    sed "s#${STAGE_DIRECTORY}/TRANSL##g"|
+    grep -v -x '/'                      |
+    filter_excluded                     > $OUTPUT
+  else
+    parse_iw $INPUT                     |
+    sort                                |
+    uniq                                |
+    install_log_filter $INSTALL_ROOT "" |
+    grep -v -x ""                       |
+    filter_excluded                     |
+    install_log_filter "" $INSTALL_ROOT |
+    exists                              >  $OUTPUT
+  fi
 
   echo "$C_LOG_COMP"                  >> $OUTPUT
   echo "$MD5_LOG"                     >> $OUTPUT
   echo "$INST_LOG"                    >> $OUTPUT
+
+}
+
+#---------------------------------------------------------------------
+##
+## Creates the install log containing all staged files. It reuses
+## the existing install log and just prepends $STAGE_DIRECTORY/TRANSL
+## to every line
+##
+## @param input log file
+## @param output log file
+##
+#---------------------------------------------------------------------
+function create_stage_install_log()  {
+  debug  "libtrack" "$FUNCNAME on $SPELL"
+  local input="$1"
+  local output="$2"
+
+  # treat the logs specially, as they weren't staged
+  grep -v "$C_LOG_COMP\|$MD5_LOG\|$INST_LOG" "$input" > "$output"
+  sed -i "s#^#$STAGE_DIRECTORY/TRANSL#" "$output"
+  echo "$C_LOG_COMP"                 >> "$output"
+  echo "$MD5_LOG"                    >> "$output"
+  echo "$INST_LOG"                   >> "$output"
 
 }
 
@@ -139,6 +284,16 @@ function create_md5list() {
     fi
   done 2>/dev/null > $OUTPUT
 }
+
+#---------------------------------------------------------------------
+## External api to note config files
+#---------------------------------------------------------------------
+function real_note_config_file() {
+  if check_if_modified "$1"; then
+    mark_file_modified "$1"
+  fi
+}
+
 
 #---------------------------------------------------------------------
 ## Notes that a file was previously modified so that its md5 is
@@ -175,6 +330,7 @@ function check_if_modified() {
     true
   fi
 }
+
 
 #---------------------------------------------------------------------
 ##
@@ -335,14 +491,10 @@ function log_adjuster() {
     fi
   fi
 
-  local TMP_SSF=$TMP_DIR/$RANDOM
-  while ! mkdir $TMP_SSF &>/dev/null; do
-    TMP_SSF=$TMP_DIR/$RANDOM
-    sleep 1
-  done
+  local TMP_SSF=$(make_safe_dir)
   local TMP_DATA=$TMP_SSF/foo.data
   local TMP_MDATA=$TMP_SSF/foo.mdata
-  
+
   seperate_state_files $input $TMP_DATA $TMP_MDATA
   {
     if [[ $cat_metadata ]] ; then
@@ -354,6 +506,7 @@ function log_adjuster() {
   } > $output
   rm $TMP_DATA $TMP_MDATA
   rmdir $TMP_SSF
+  return 0
 }
 
 #---------------------------------------------------------------------
@@ -370,19 +523,51 @@ function seperate_state_files() {
   local REAL_STATE_DIR=${STATE_DIRECTORY#$STATE_ROOT}
 
   # the input file is almost certainly a pipe, and things get weird
-  # since we have to grep twice, so just dump the data into a unique
-  # file, the loop below shouldn't go forever unless there's ~30,000 pipes
+  # since we have to grep twice, so just dump the data into a unique file
 
-  local FILE=$TMP_DIR/ssf.$RANDOM
-  while test -e $FILE; do
-    FILE=$TMP_DIR/ssf.$RANDOM
-  done
+  local TMP_SSF=$(make_safe_dir)
+  local FILE=$TMP_SSF/ssf
   cat $1 > $FILE
   grep -v "$REAL_LOG_DIR\|$REAL_STATE_DIR" $FILE | grep -xv '' > $2
   grep    "$REAL_LOG_DIR\|$REAL_STATE_DIR" $FILE | grep -xv '' > $3
   rm $FILE
+  rmdir $TMP_SSF
   return 0
 }
+
+#---------------------------------------------------------------------
+## Try to make a unique directory using $RANDOM, leverage the fact that
+## two simultaneous mkdir's will have one succeed and the other fail.
+##
+## This is run from log_adjuster primarily which may be invoked several
+## times in a pipe, when this happens, bash does a fork, but does not
+## seem to reseed the random number generator, causing a high rate of
+## collisions. This is not easily reproducable outside of sorcery at
+## the time of writing, but inside it happens nearly everytime with bash
+## 3.1. This may actually be a bash 3.1 bug.
+##
+## The collisions aren't bad necessarily, but they result in un-necesary
+## delay.
+##
+## Setting RANDOM re-seeds the random number generator.
+##
+## Despite the fact that the subshell and invocation of date are slow
+## the consequence for not doing them are worse. The nano-seconds
+## are usually going to be different between forks so the liklihood
+## of a collision is greatly reduced.
+#---------------------------------------------------------------------
+function make_safe_dir() { (
+  RANDOM=$(date "+%N")
+  local TMP_SSF=$TMP_DIR/$RANDOM
+  while ! mkdir "$TMP_SSF" &> /dev/null; do
+    RANDOM=$(date "+%N")
+    TMP_SSF=$TMP_DIR/$RANDOM
+    sleep .1
+    debug "libtrack" "safe dir collision on $TMP_SSF"
+  done
+  echo $TMP_SSF
+  return 0
+) }
 
 #---------------------------------------------------------------------
 ## @License
diff --git a/var/lib/sorcery/modules/libunpack b/var/lib/sorcery/modules/libunpack
--- a/var/lib/sorcery/modules/libunpack
+++ b/var/lib/sorcery/modules/libunpack
@@ -104,11 +104,11 @@
 ## below) will silently fail over to the next check.  The cascade order is:
 ##  GPG, HASH, IGNORE, MISSING
 ##
-## The cascade setup allows you to place a higher bit checksum earlier 
-## in the cascade and even if the binary doesn't work it will just print 
-## out an abort query which can be said no to and it will continue to 
-## fail over to the lower bit checksum that should be available in 
-## coreutils (like sha1/md5).  That's if you're not using gpg, which is 
+## The cascade setup allows you to place a higher bit checksum earlier
+## in the cascade and even if the binary doesn't work it will just print
+## out an abort query which can be said no to and it will continue to
+## fail over to the lower bit checksum that should be available in
+## coreutils (like sha1/md5).  That's if you're not using gpg, which is
 ## preferred.  If multiple hashes are included of different ciphers, the
 ## user can abort on either that go bad, so it can be considered a
 ## security increase to have more than one, but only if the harder cipher
@@ -132,7 +132,7 @@ function real_unpack_file() {
       1) return 1 ;; # verification failed
       0) uncompress_unpack ${!SVAR}; return $? ;;
   esac
-  
+
   if false; then # <------ here's the switch to disable oldworld -------
     debug "libgrimoire" "falling back to missing verification"
     unpack_missing "${!SVAR}"
@@ -185,8 +185,8 @@ function real_verify_file() {
 
 
 #---------------------------------------------------------------------
-## @param filename 
-## @param compressor 
+## @param filename
+## @param compressor
 ## @Stdout uncompressed
 ##
 ## Just uncompresses the file, but does not expand it. i.e. bunzip
@@ -211,8 +211,8 @@ function uncompress_core() {
 
 
 #---------------------------------------------------------------------
-## @param filename 
-## @param compressor 
+## @param filename
+## @param compressor
 ## @Stdout uncompressed
 ##
 ## unpack_core takes the uncompressed stream and turns it into the
@@ -226,7 +226,7 @@ function unpack_core() {
   case  "$2"  in
             bzip2|gzip|compress*|tar)
                     tar   --no-same-owner --no-same-permissions -xf \
-		          /dev/stdin 2> /dev/null  ||  cat > /dev/null ;;
+                    /dev/stdin 2> /dev/null  ||  cat > /dev/null ;;
               Zip)  cat /dev/stdin >/dev/null   #get rid of unused output
                     unzip  -q  "$1"                                    ;;
               RPM)  cpio  -idm < /dev/stdin                            ;;
@@ -282,7 +282,7 @@ function unpack_spell_required() {
   if ! spell_ok "$1" && ! smgl_which $2 x &> /dev/null; then
     query "This spell has an option to check its integrity via spell "\
 "${SPELL_COLOR}${1}${QUERY_COLOR} with the $2 command for $3, you might consider installing it. "\
-"Abort?" n && 
+"Abort?" n &&
       return 1 ||
         return 200
   else
@@ -352,7 +352,7 @@ function is_allowed_hash() {
     rc=1
   elif [[ "$VRF_ALLOW_NEW_HASHES" == "on" ]]
   then
-    message "${MESSAGE_COLOR}Allowing new hash${hash}${DEFAULT_COLOR}"
+    message "${MESSAGE_COLOR}Allowing new hash ${hash}${DEFAULT_COLOR}"
     if is_allowed_verf_level $HASHLEVEL ; then rc=0 ; else rc=1; fi
   else
     message "${PROBLEM_COLOR}Disallowing new hash ${hash}${DEFAULT_COLOR}"
@@ -362,12 +362,12 @@ function is_allowed_hash() {
 }
 
 #---------------------------------------------------------------------
-## @param file to unpack 
+## @param file to unpack
 ## @param gpg public key file (.gpg) ":" gpg signature file  (.asc)
 ##
-## Given a file, unpack checks the gpg signature for that file, and, if 
-## appropriate, runs the decompression program for that file, as well as 
-## untar'ing the file. Note: zip is a special case because it doesn't 
+## Given a file, unpack checks the gpg signature for that file, and, if
+## appropriate, runs the decompression program for that file, as well as
+## untar'ing the file. Note: zip is a special case because it doesn't
 ## work with streams.
 ##
 #---------------------------------------------------------------------
@@ -399,7 +399,14 @@ function unpack_gpg() {
   rc="$?"
   case "$rc" in
     0)
-      if is_allowed_hash $GPGALGO_USED $GPGLEVEL ; then rc=0 ; else rc=1 ; fi
+      local algo
+      rc=1
+      for algo in $GPGALGO_USED; do
+        if is_allowed_hash "$algo" "$GPGLEVEL"; then
+          rc=0
+          break
+        fi
+      done
       ;;
     3) message_file="Signature" ;;
     4) message_file="Source" ;;
@@ -409,10 +416,10 @@ function unpack_gpg() {
   then
       message "${PROBLEM_COLOR}AHHH!!! ${message_file} file not found${DEFAULT_COLOR}"
   fi
-  if [ "$rc" -eq 200 ]; then 
+  if [ "$rc" -eq 200 ]; then
     return 200
   fi
-  
+
   gpg_user_query $rc $SPELL spell || return 1
   return 0
 
@@ -420,12 +427,12 @@ function unpack_gpg() {
 
 
 #---------------------------------------------------------------------
-## @param file to unpack 
+## @param file to unpack
 ## @param algorithm ":" hashsum
 ##
-## Given a file, unpack checks the hash for that file, and, if 
-## appropriate, runs the decompression program for that file, as well as 
-## untar'ing the file. Note: zip is a special case because it doesn't 
+## Given a file, unpack checks the hash for that file, and, if
+## appropriate, runs the decompression program for that file, as well as
+## untar'ing the file. Note: zip is a special case because it doesn't
 ## work with streams.
 ##
 #---------------------------------------------------------------------
@@ -448,13 +455,13 @@ function unpack_hash() {
 
     if [[ "$ALGORITHM" == md5 ]] || [[ "$ALGORITHM" == sha1 ]] ; then
       unpack_spell_required coreutils "${ALGORITHM}sum" "$ALGORITHM" ||
-        return "$?" 
+        return "$?"
       HASH="$(${ALGORITHM}sum "$FILENAME" | cut -d' ' -f1)"
     else
       unpack_spell_required gnupg gpg "$ALGORITHM" || return "$?"
       if list_find "$(gpg_get_hashes)" $ALGORITHM; then
         HASH="$(gpg_hashsum "${ALGORITHM}" "$FILENAME" | cut -d' ' -f1)"
-      else 
+      else
         message "${PROBLEM_COLOR}Algorithm $ALGORITHM is not"\
                 "known!${DEFAULT_COLOR}"
         return 200
@@ -468,7 +475,8 @@ function unpack_hash() {
       error_message "$HASH (computed) != $HASHSUM (expected)!$DEFAULT_COLOR" &&
       hash_user_query 1 "$SPELL" spell || return 1
     else
-      if is_allowed_hash ${ALGORITHM} ${HLEVEL} ; then rc=0 ; else rc=1 ; fi
+      is_allowed_hash "$ALGORITHM" "$HLEVEL"
+      rc=$?
       hash_user_query $rc "$SPELL" spell || return 1
     fi
   else
@@ -479,11 +487,11 @@ function unpack_hash() {
 
 #--------------------------------------------------------------------
 ## @param return code from unpack_hash
-## @param spell name 
-## 
+## @param spell name
+##
 ## Does some basic output to tell the user what failed and how then calls
 ## unpack_file_user_query
-## Returns 0 if hash succeeded otherwise returns 1 if unpack_file_user_query 
+## Returns 0 if hash succeeded otherwise returns 1 if unpack_file_user_query
 ## fails
 ##
 #--------------------------------------------------------------------
@@ -491,7 +499,7 @@ function hash_user_query() {
   local rc=$1
   local spell=$2
   case "$rc" in
-    0) 
+    0)
       message "${MESSAGE_COLOR}hash verification succeeded${DEFAULT_COLOR}"
       ;;
     *)
@@ -505,7 +513,7 @@ function hash_user_query() {
 #--------------------------------------------------------------------
 ## @param return code from the unpack_gpg or unpack_hash
 ##
-## checks MD5SUM_DL to abort or not 
+## checks MD5SUM_DL to abort or not
 ## Returns what query returns if it's called
 ##
 #--------------------------------------------------------------------
@@ -526,12 +534,12 @@ function unpack_file_user_query() {
 }
 
 #---------------------------------------------------------------------
-## @param file to unpack 
+## @param file to unpack
 ## @param reason to ignore it, one of: volatile unversioned signature
 ##
-## Given a file, unpack checks the ignore rules for that file, and, if 
-## appropriate, runs the decompression program for that file, as well as 
-## untar'ing the file. Note: zip is a special case because it doesn't 
+## Given a file, unpack checks the ignore rules for that file, and, if
+## appropriate, runs the decompression program for that file, as well as
+## untar'ing the file. Note: zip is a special case because it doesn't
 ## work with streams.
 ##
 #---------------------------------------------------------------------
@@ -560,12 +568,12 @@ ask_risky|ask_ignore)  query "Abort?" "n"         && return 1   ||  return 0 ;;
 
 
 #---------------------------------------------------------------------
-## @param file to unpack 
+## @param file to unpack
 ## @param reason to ignore it, one of: volatile unversioned signature
 ##
-## Given a file, unpack checks the ignore rules for that file, and, if 
-## appropriate, runs the decompression program for that file, as well as 
-## untar'ing the file. Note: zip is a special case because it doesn't 
+## Given a file, unpack checks the ignore rules for that file, and, if
+## appropriate, runs the decompression program for that file, as well as
+## untar'ing the file. Note: zip is a special case because it doesn't
 ## work with streams.
 ##
 #---------------------------------------------------------------------
@@ -591,10 +599,10 @@ function unpack_missing() {
 
 
 #---------------------------------------------------------------------
-## @param file to unpack 
+## @param file to unpack
 ##
-## Given a file, runs the decompression program for that file, as well as 
-## untar'ing the file. 
+## Given a file, runs the decompression program for that file, as well as
+## untar'ing the file.
 ##
 #---------------------------------------------------------------------
 function uncompress_unpack() {
@@ -617,7 +625,7 @@ function uncompress_unpack() {
 }
 
 #---------------------------------------------------------------------
-## @param file to unpack 
+## @param file to unpack
 ##
 ## Interface to unpack a file without any verification.
 ##
@@ -660,7 +668,7 @@ function locate_spell_file() {
 
 #---------------------------------------------------------------------
 ## @Type API
-## @param file to unpack 
+## @param file to unpack
 ## @param md5sum
 ##
 ## Given a file, unpack runs the decompression program for that file,
@@ -748,13 +756,13 @@ ask_risky|ask_ignore)  query "Abort?" "n"         && return 1   ||  return 0 ;;
 
 
 #---------------------------------------------------------------------
-## @param filename 
-## @param compressor 
-## @param md5 
+## @param filename
+## @param compressor
+## @param md5
 ## @Stdout uncompressed
 ##
-## Uncompress_md5 dumps the expanded file via tee to md5_tar_check where it 
-## is gobbled up by the bitbucket.  It also dumps the main stream out to 
+## Uncompress_md5 dumps the expanded file via tee to md5_tar_check where it
+## is gobbled up by the bitbucket.  It also dumps the main stream out to
 ## stdout.
 ##
 #---------------------------------------------------------------------
@@ -762,7 +770,7 @@ function uncompress_md5() {
   debug "libgrimoire" "uncompress_md5 - $*"
 
   # This is here so Duff's super debugging info doesn't screw the next step up
-  set +x 
+  set +x
 
   # Outer subshell is necessary to redirect stderr to stdout
   (
